import React from 'react'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { ScrollArea } from "@/components/ui/scroll-area"

interface City {
  name: string
  rank: number
}

const ILLINOIS_CITIES: City[] = [
  { rank: 1, name: "Chicago" },
  { rank: 2, name: "Aurora" },
  { rank: 3, name: "Joliet" },
  { rank: 4, name: "Naperville" },
  { rank: 5, name: "Rockford" },
  { rank: 6, name: "Elgin" },
  { rank: 7, name: "Springfield" },
  { rank: 8, name: "Peoria" },
  { rank: 9, name: "Champaign" },
  { rank: 10, name: "Waukegan" },
  { rank: 11, name: "Cicero" },
  { rank: 12, name: "Bloomington" },
  { rank: 13, name: "Schaumburg" },
  { rank: 14, name: "Bolingbrook" },
  { rank: 15, name: "Evanston" },
  { rank: 16, name: "Arlington Heights" },
  { rank: 17, name: "Decatur" },
  { rank: 18, name: "Skokie" },
  { rank: 19, name: "Palatine" },
  { rank: 20, name: "Des Plaines" },
  { rank: 21, name: "Orland Park" },
  { rank: 22, name: "Oak Lawn" },
  { rank: 23, name: "Berwyn" },
  { rank: 24, name: "Mount Prospect" },
  { rank: 25, name: "Tinley Park" },
  { rank: 26, name: "Wheaton" },
  { rank: 27, name: "Normal" },
  { rank: 28, name: "Oak Park" },
  { rank: 29, name: "Downers Grove" },
  { rank: 30, name: "Hoffman Estates" },
  { rank: 31, name: "Plainfield" },
  { rank: 32, name: "Glenview" },
  { rank: 33, name: "Elmhurst" },
  { rank: 34, name: "Lombard" },
  { rank: 35, name: "Buffalo Grove" },
  { rank: 36, name: "Moline" },
  { rank: 37, name: "Crystal Lake" },
  { rank: 38, name: "Romeoville" },
  { rank: 39, name: "Belleville" },
  { rank: 40, name: "DeKalb" },
  { rank: 41, name: "Bartlett" },
  { rank: 42, name: "Carol Stream" },
  { rank: 43, name: "Quincy" },
  { rank: 44, name: "Urbana" },
  { rank: 45, name: "Oswego" },
  { rank: 46, name: "Park Ridge" },
  { rank: 47, name: "Wheeling" },
  { rank: 48, name: "Streamwood" },
  { rank: 49, name: "Carpentersville" },
  { rank: 50, name: "Rock Island" },
  { rank: 51, name: "Hanover Park" },
  { rank: 52, name: "Addison" },
  { rank: 53, name: "Calumet City" },
  { rank: 54, name: "Northbrook" },
  { rank: 55, name: "Woodridge" },
  { rank: 56, name: "St. Charles" },
  { rank: 57, name: "Glendale Heights" },
  { rank: 58, name: "Mundelein" },
  { rank: 59, name: "O'Fallon" },
  { rank: 60, name: "Pekin" },
  { rank: 61, name: "Elk Grove Village" },
  { rank: 62, name: "North Chicago" },
  { rank: 63, name: "Highland Park" },
  { rank: 64, name: "Algonquin" },
  { rank: 65, name: "Gurnee" },
  { rank: 66, name: "Niles" },
  { rank: 67, name: "Galesburg" },
  { rank: 68, name: "Lake Hills" },
  { rank: 69, name: "McHenry" },
  { rank: 70, name: "Huntley" },
  { rank: 71, name: "New Lenox" },
  { rank: 72, name: "Glen Ellyn" },
  { rank: 73, name: "Danville" },
  { rank: 74, name: "Burbank" },
  { rank: 75, name: "Lansing" },
  { rank: 76, name: "Granite City" },
  { rank: 77, name: "Wilmette" },
  { rank: 78, name: "Lockport" },
  { rank: 79, name: "Edwardsville" },
  { rank: 80, name: "Round Lake Beach" },
  { rank: 81, name: "Vernon Hills" },
  { rank: 82, name: "Batavia" },
  { rank: 83, name: "Oak Forest" },
  { rank: 84, name: "Chicago Heights" },
  { rank: 85, name: "Woodstock" },
  { rank: 86, name: "Yorkville" },
  { rank: 87, name: "Belvidere" },
  { rank: 88, name: "West Chicago" },
  { rank: 89, name: "Alton" },
  { rank: 90, name: "Homer Glen" },
  { rank: 91, name: "South Elgin" },
  { rank: 92, name: "Zion" },
  { rank: 93, name: "Westmont" },
  { rank: 94, name: "Morton Grove" },
  { rank: 95, name: "Collinsville" },
  { rank: 96, name: "Kankakee" },
  { rank: 97, name: "Melrose Park" },
  { rank: 98, name: "Loves Park" },
  { rank: 99, name: "Lisle" },
  { rank: 100, name: "Rolling Meadows" },
  { rank: 101, name: "Elmwood Park" },
  { rank: 102, name: "Freeport" },
  { rank: 103, name: "Maywood" },
  { rank: 104, name: "Machesney Park" },
  { rank: 105, name: "Montgomery" },
  { rank: 106, name: "Roselle" },
  { rank: 107, name: "Bloomingdale" },
  { rank: 108, name: "East Peoria" },
  { rank: 109, name: "Darien" },
  { rank: 110, name: "Villa Park" },
  { rank: 111, name: "Carbondale" },
  { rank: 112, name: "Blue Island" },
  { rank: 113, name: "Frankfort" },
  { rank: 114, name: "Geneva" },
  { rank: 115, name: "Grayslake" },
  { rank: 116, name: "East Moline" },
  { rank: 117, name: "Park Forest" },
  { rank: 118, name: "Libertyville" },
  { rank: 119, name: "South Holland" },
  { rank: 120, name: "Dolton" },
  { rank: 121, name: "Crest Hill" },
  { rank: 122, name: "Mokena" },
  { rank: 123, name: "Lake Zurich" },
  { rank: 124, name: "Lake Forest" },
  { rank: 125, name: "North Aurora" },
  { rank: 126, name: "Harvey" },
  { rank: 127, name: "Deerfield" },
  { rank: 128, name: "Evergreen Park" },
  { rank: 129, name: "Ottawa" },
  { rank: 130, name: "Sycamore" },
  { rank: 131, name: "Shorewood" },
  { rank: 132, name: "Round Lake" },
  { rank: 133, name: "Brookfield" },
  { rank: 134, name: "Homewood" },
  { rank: 135, name: "Bensenville" },
  { rank: 136, name: "Matteson" },
  { rank: 137, name: "Cary" },
  { rank: 138, name: "Bourbonnais" },
  { rank: 139, name: "Alsip" },
  { rank: 140, name: "Franklin Park" },
  { rank: 141, name: "Bellwood" },
  { rank: 142, name: "Morton" },
  { rank: 143, name: "Godfrey" },
  { rank: 144, name: "Palos Hills" },
  { rank: 145, name: "Lemont" },
  { rank: 146, name: "East St. Louis" },
  { rank: 147, name: "Hinsdale" },
  { rank: 148, name: "Jacksonville" },
  { rank: 149, name: "Charleston" },
  { rank: 150, name: "Cahokia Heights" },
  { rank: 151, name: "Marion" },
  { rank: 152, name: "Mattoon" },
  { rank: 153, name: "Bridgeview" },
  { rank: 154, name: "Fairview Heights" },
  { rank: 155, name: "Westchester" },
  { rank: 156, name: "Country Club Hills" },
  { rank: 157, name: "Washington" },
  { rank: 158, name: "Warrenville" },
  { rank: 159, name: "La Grange" },
  { rank: 160, name: "Bradley" },
  { rank: 161, name: "Prospect Heights" },
  { rank: 162, name: "Dixon" },
  { rank: 163, name: "Shiloh" },
  { rank: 164, name: "Antioch" },
  { rank: 165, name: "Macomb" },
  { rank: 166, name: "Morris" },
  { rank: 167, name: "Chatham" },
  { rank: 168, name: "Swansea" },
  { rank: 169, name: "Norridge" },
  { rank: 170, name: "Sterling" },
  { rank: 171, name: "Channahon" },
  { rank: 172, name: "Lindenhurst" },
  { rank: 173, name: "Mount Vernon" },
  { rank: 174, name: "Beach Park" },
  { rank: 175, name: "Glen Carbon" },
  { rank: 176, name: "Wauconda" },
  { rank: 177, name: "Hickory Hills" },
  { rank: 178, name: "Wood Dale" },
  { rank: 179, name: "Chicago Ridge" },
  { rank: 180, name: "Midlothian" },
  { rank: 181, name: "Forest Park" },
  { rank: 182, name: "Western Springs" },
  { rank: 183, name: "Lincoln" },
  { rank: 184, name: "Plano" },
  { rank: 185, name: "Minooka" },
  { rank: 186, name: "La Grange Park" },
  { rank: 187, name: "Canton" },
  { rank: 188, name: "Lincolnwood" },
  { rank: 189, name: "Hazel Crest" },
  { rank: 190, name: "Effingham" },
  { rank: 191, name: "Streator" },
  { rank: 192, name: "Richton Park" },
  { rank: 193, name: "Winnetka" },
  { rank: 194, name: "Kewanee" },
  { rank: 195, name: "Herrin" },
  { rank: 196, name: "Northlake" },
  { rank: 197, name: "Justice" },
  { rank: 198, name: "Rantoul" },
  { rank: 199, name: "Centralia" },
  { rank: 200, name: "Pingree Grove" },
  { rank: 201, name: "Palos Heights" },
  { rank: 202, name: "Troy" },
  { rank: 203, name: "Waterloo" },
  { rank: 204, name: "River Forest" },
  { rank: 205, name: "Gages Lake" },
  { rank: 206, name: "Schiller Park" },
  { rank: 207, name: "Burr Ridge" },
  { rank: 208, name: "Markham" },
  { rank: 209, name: "Pontiac" },
  { rank: 210, name: "Columbia" },
  { rank: 211, name: "Manhattan" },
  { rank: 212, name: "Roscoe" },
  { rank: 213, name: "Campton Hills" },
  { rank: 214, name: "Fox Lake" },
  { rank: 215, name: "Mahomet" },
  { rank: 216, name: "Summit" },
  { rank: 217, name: "Barrington" },
  { rank: 218, name: "Worth" },
  { rank: 219, name: "Crestwood" },
  { rank: 220, name: "Wood River" },
  { rank: 221, name: "River Grove" },
  { rank: 222, name: "Taylorville" },
  { rank: 223, name: "Lyons" },
  { rank: 224, name: "Winfield" },
  { rank: 225, name: "Riverdale" },
  { rank: 226, name: "Highland" },
  { rank: 227, name: "Boulder Hill" },
  { rank: 228, name: "Peru" },
  { rank: 229, name: "Hawthorn Woods" },
  { rank: 230, name: "LaSalle" },
  { rank: 231, name: "Frankfort Square" },
  { rank: 232, name: "Sauk Village" },
  { rank: 233, name: "Harvard" },
  { rank: 234, name: "Itasca" },
  { rank: 235, name: "Rochelle" },
  { rank: 236, name: "Sugar Grove" },
  { rank: 237, name: "Steger" },
  { rank: 238, name: "Manteno" },
  { rank: 239, name: "Bethalto" },
  { rank: 240, name: "Flossmoor" },
  { rank: 241, name: "Lynwood" },
  { rank: 242, name: "Willowbrook" },
  { rank: 243, name: "Mascoutah" },
  { rank: 244, name: "Gilberts" },
  { rank: 245, name: "Savoy" },
  { rank: 246, name: "Riverside" },
  { rank: 247, name: "Lake Villa" },
  { rank: 248, name: "Rock Falls" },
  { rank: 249, name: "Clarendon Hills" },
  { rank: 250, name: "Harwood Heights" },
  { rank: 251, name: "Glencoe" },
  { rank: 252, name: "Monmouth" },
  { rank: 253, name: "Olney" },
  { rank: 254, name: "Maryville" },
  { rank: 255, name: "Crete" },
  { rank: 256, name: "Jerseyville" },
  { rank: 257, name: "Long Grove" },
  { rank: 258, name: "Hampshire" },
  { rank: 259, name: "Glenwood" },
  { rank: 260, name: "Oak Brook" },
  { rank: 261, name: "Island Lake" },
  { rank: 262, name: "Paris" },
  { rank: 263, name: "Lincolnshire" },
  { rank: 264, name: "West Dundee" },
  { rank: 265, name: "South Beloit" },
  { rank: 266, name: "Silvis" },
  { rank: 267, name: "Park City" },
  { rank: 268, name: "Harrisburg" },
  { rank: 269, name: "Hillside" },
  { rank: 270, name: "Round Lake Park" },
  { rank: 271, name: "Rockton" },
  { rank: 272, name: "Broadview" },
  { rank: 273, name: "Princeton" },
  { rank: 274, name: "Marengo" },
  { rank: 275, name: "Vandalia" },
  { rank: 276, name: "Volo" },
  { rank: 277, name: "Sandwich" },
  { rank: 278, name: "Inverness" },
  { rank: 279, name: "West Frankfort" },
  { rank: 280, name: "Salem" },
  { rank: 281, name: "Robinson" },
  { rank: 282, name: "North Riverside" },
  { rank: 283, name: "University Park" },
  { rank: 284, name: "Greenville" },
  { rank: 285, name: "Murphysboro" },
  { rank: 286, name: "Mendota" },
  { rank: 287, name: "Clinton" },
  { rank: 288, name: "Stickney" },
  { rank: 289, name: "Chester" },
  { rank: 290, name: "Elburn" },
  { rank: 291, name: "Mount Carmel" },
  { rank: 292, name: "Calumet Park" },
  { rank: 293, name: "Benton" },
  { rank: 294, name: "Litchfield" },
  { rank: 295, name: "Winthrop Harbor" },
  { rank: 296, name: "Geneseo" },
  { rank: 297, name: "Orland Hills" },
  { rank: 298, name: "Johnsburg" },
  { rank: 299, name: "Lakemoor" },
  { rank: 300, name: "Braidwood" },
  { rank: 301, name: "Countryside" },
  { rank: 302, name: "Monticello" },
  { rank: 303, name: "Chillicothe" },
  { rank: 304, name: "Candlewick Lake" },
  { rank: 305, name: "Mount Zion" },
  { rank: 306, name: "Coal City" },
  { rank: 307, name: "Carterville" },
  { rank: 308, name: "Pontoon Beach" },
  { rank: 309, name: "Hillsboro" },
  { rank: 310, name: "Bartonville" },
  { rank: 311, name: "Metropolis" },
  { rank: 312, name: "Peoria Heights" },
  { rank: 313, name: "Beardstown" },
  { rank: 314, name: "Du Quoin" },
  { rank: 315, name: "Willow Springs" },
  { rank: 316, name: "Lake Holiday" },
  { rank: 317, name: "East Alton" },
  { rank: 318, name: "Wilmington" },
  { rank: 319, name: "Spring Grove" },
  { rank: 320, name: "Lake Bluff" },
  { rank: 321, name: "Genoa" },
  { rank: 322, name: "Carlinville" },
  { rank: 323, name: "Northfield" },
  { rank: 324, name: "Grandwood Park" },
  { rank: 325, name: "Spring Valley" },
  { rank: 326, name: "Highwood" },
  { rank: 327, name: "Posen" },
  { rank: 328, name: "Wonder Lake" },
  { rank: 329, name: "Eureka" },
  { rank: 330, name: "Poplar Grove" },
  { rank: 331, name: "Lake Barrington" },
  { rank: 332, name: "Monee" },
  { rank: 333, name: "Berkeley" },
  { rank: 334, name: "Pana" }
]

interface IllinoisCitySelectorProps {
  onCitySelect: (city: City) => void
  selectedCities: string[]
}

const IllinoisCitySelector: React.FC<IllinoisCitySelectorProps> = ({ onCitySelect, selectedCities }) => {
  return (
    <div className="space-y-2">
      <label htmlFor="illinois-city-select" className="block text-sm font-medium text-[#E4B649]">
        Select an Illinois City
      </label>
      <Select onValueChange={(value) => {
        const selectedCity = ILLINOIS_CITIES.find(city => city.name === value)
        if (selectedCity) onCitySelect(selectedCity)
      }}>
        <SelectTrigger id="illinois-city-select" className="w-full bg-black/50 border-[#E4B649]/20 text-white">
          <SelectValue placeholder="Choose a city" />
        </SelectTrigger>
        <SelectContent className="bg-black border-[#E4B649]/20">
          <ScrollArea className="h-[200px]">
            {ILLINOIS_CITIES.map((city) => (
              <SelectItem 
                key={city.rank} 
                value={city.name}
                className="text-white hover:bg-[#E4B649]/20"
                disabled={selectedCities.includes(city.name)}
              >
                {city.name}
              </SelectItem>
            ))}
          </ScrollArea>
        </SelectContent>
      </Select>
      <p className="text-xs text-[#E4B649]/70">
        * You can select up to 10 cities from Illinois
      </p>
    </div>
  )
}

export default IllinoisCitySelector

