import React from 'react'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { ScrollArea } from "@/components/ui/scroll-area"

interface City {
  name: string
  rank: number
}

const MASSACHUSETTS_CITIES: City[] = [
  { rank: 1, name: "Boston" },
  { rank: 2, name: "Worcester" },
  { rank: 3, name: "Springfield" },
  { rank: 4, name: "Cambridge" },
  { rank: 5, name: "Lowell" },
  { rank: 6, name: "Brockton" },
  { rank: 7, name: "Lynn" },
  { rank: 8, name: "Quincy" },
  { rank: 9, name: "New Bedford" },
  { rank: 10, name: "Fall River" },
  { rank: 11, name: "Newton" },
  { rank: 12, name: "Lawrence" },
  { rank: 13, name: "Somerville" },
  { rank: 14, name: "Framingham" },
  { rank: 15, name: "Haverhill" },
  { rank: 16, name: "Plymouth" },
  { rank: 17, name: "Malden" },
  { rank: 18, name: "Waltham" },
  { rank: 19, name: "Brookline" },
  { rank: 20, name: "Taunton" },
  { rank: 21, name: "Weymouth Town" },
  { rank: 22, name: "Medford" },
  { rank: 23, name: "Revere" },
  { rank: 24, name: "Chicopee" },
  { rank: 25, name: "Peabody" },
  { rank: 26, name: "Methuen Town" },
  { rank: 27, name: "Everett" },
  { rank: 28, name: "Barnstable Town" },
  { rank: 29, name: "Attleboro" },
  { rank: 30, name: "Arlington" },
  { rank: 31, name: "Salem" },
  { rank: 32, name: "Leominster" },
  { rank: 33, name: "Pittsfield" },
  { rank: 34, name: "Beverly" },
  { rank: 35, name: "Woburn" },
  { rank: 36, name: "Billerica" },
  { rank: 37, name: "Fitchburg" },
  { rank: 38, name: "Marlborough" },
  { rank: 39, name: "Westfield" },
  { rank: 40, name: "Shrewsbury" },
  { rank: 41, name: "Braintree Town" },
  { rank: 42, name: "Chelsea" },
  { rank: 43, name: "Holyoke" },
  { rank: 44, name: "Andover" },
  { rank: 45, name: "Natick" },
  { rank: 46, name: "Chelmsford" },
  { rank: 47, name: "Watertown Town" },
  { rank: 48, name: "Randolph Town" },
  { rank: 49, name: "Lexington" },
  { rank: 50, name: "Dartmouth" },
  { rank: 51, name: "Franklin Town" },
  { rank: 52, name: "Falmouth" },
  { rank: 53, name: "Dracut" },
  { rank: 54, name: "Needham" },
  { rank: 55, name: "North Andover" },
  { rank: 56, name: "Tewksbury" },
  { rank: 57, name: "Norwood" },
  { rank: 58, name: "Wellesley" },
  { rank: 59, name: "Milford" },
  { rank: 60, name: "Gloucester" },
  { rank: 61, name: "Melrose" },
  { rank: 62, name: "Northampton" },
  { rank: 63, name: "Stoughton" },
  { rank: 64, name: "Bridgewater Town" },
  { rank: 65, name: "Saugus" },
  { rank: 66, name: "Agawam Town" },
  { rank: 67, name: "Wakefield" },
  { rank: 68, name: "West Springfield Town" },
  { rank: 69, name: "Milton" },
  { rank: 70, name: "Danvers" },
  { rank: 71, name: "Burlington" },
  { rank: 72, name: "Belmont" },
  { rank: 73, name: "Marshfield" },
  { rank: 74, name: "Walpole" },
  { rank: 75, name: "Reading" },
  { rank: 76, name: "Easton" },
  { rank: 77, name: "Yarmouth" },
  { rank: 78, name: "Dedham" },
  { rank: 79, name: "Canton" },
  { rank: 80, name: "Middleborough" },
  { rank: 81, name: "Westford" },
  { rank: 82, name: "Hingham" },
  { rank: 83, name: "Acton" },
  { rank: 84, name: "Mansfield" },
  { rank: 85, name: "Wilmington" },
  { rank: 86, name: "Wareham" },
  { rank: 87, name: "Winchester" },
  { rank: 88, name: "Stoneham" },
  { rank: 89, name: "Westborough" },
  { rank: 90, name: "Gardner" },
  { rank: 91, name: "Ludlow" },
  { rank: 92, name: "Marblehead" },
  { rank: 93, name: "Bourne" },
  { rank: 94, name: "Sandwich" },
  { rank: 95, name: "Grafton" },
  { rank: 96, name: "Hudson" },
  { rank: 97, name: "Holden" },
  { rank: 98, name: "Hopkinton" },
  { rank: 99, name: "Sudbury" },
  { rank: 100, name: "Scituate" },
  { rank: 101, name: "Norton" },
  { rank: 102, name: "Newburyport" },
  { rank: 103, name: "Ashland" },
  { rank: 104, name: "Foxborough" },
  { rank: 105, name: "Sharon" },
  { rank: 106, name: "Pembroke" },
  { rank: 107, name: "Somerset" },
  { rank: 108, name: "Winthrop Town" },
  { rank: 109, name: "Concord" },
  { rank: 110, name: "South Hadley" },
  { rank: 111, name: "Southbridge Town" },
  { rank: 112, name: "Bellingham" },
  { rank: 113, name: "Rockland" },
  { rank: 114, name: "Webster" },
  { rank: 115, name: "Swansea" },
  { rank: 116, name: "Amesbury Town" },
  { rank: 117, name: "Abington" },
  { rank: 118, name: "Auburn" },
  { rank: 119, name: "Northbridge" },
  { rank: 120, name: "Westport" },
  { rank: 121, name: "North Reading" },
  { rank: 122, name: "East Longmeadow" },
  { rank: 123, name: "Duxbury" },
  { rank: 124, name: "Westwood" },
  { rank: 125, name: "Easthampton Town" },
  { rank: 126, name: "Fairhaven" },
  { rank: 127, name: "Raynham" },
  { rank: 128, name: "Seekonk" },
  { rank: 129, name: "Swampscott" },
  { rank: 130, name: "Northborough" },
  { rank: 131, name: "Longmeadow" },
  { rank: 132, name: "Clinton" },
  { rank: 133, name: "Whitman" },
  { rank: 134, name: "Mashpee" },
  { rank: 135, name: "Belchertown" },
  { rank: 136, name: "Holliston" },
  { rank: 137, name: "Dennis" },
  { rank: 138, name: "Hanover" },
  { rank: 139, name: "Uxbridge" },
  { rank: 140, name: "Wilbraham" },
  { rank: 141, name: "Bedford" },
  { rank: 142, name: "Nantucket" },
  { rank: 143, name: "East Bridgewater" },
  { rank: 144, name: "Kingston" },
  { rank: 145, name: "Millbury" },
  { rank: 146, name: "Ipswich" },
  { rank: 147, name: "Wayland" },
  { rank: 148, name: "Medway" },
  { rank: 149, name: "Rehoboth" },
  { rank: 150, name: "Harwich" },
  { rank: 151, name: "Charlton" },
  { rank: 152, name: "Oxford" },
  { rank: 153, name: "Lynnfield" },
  { rank: 154, name: "Medfield" },
  { rank: 155, name: "Wrentham" },
  { rank: 156, name: "Tyngsborough" },
  { rank: 157, name: "North Adams" },
  { rank: 158, name: "Palmer Town" },
  { rank: 159, name: "Lakeville" },
  { rank: 160, name: "Athol" },
  { rank: 161, name: "Spencer" },
  { rank: 162, name: "Lunenburg" },
  { rank: 163, name: "Dudley" },
  { rank: 164, name: "Pepperell" },
  { rank: 165, name: "Carver" },
  { rank: 166, name: "Weston" },
  { rank: 167, name: "Norfolk" },
  { rank: 168, name: "Groton" },
  { rank: 169, name: "Norwell" },
  { rank: 170, name: "Holbrook" },
  { rank: 171, name: "Leicester" },
  { rank: 172, name: "Acushnet" },
  { rank: 173, name: "Maynard" },
  { rank: 174, name: "Hanson" },
  { rank: 175, name: "Winchendon" },
  { rank: 176, name: "Southborough" },
  { rank: 177, name: "Brewster" },
  { rank: 178, name: "Littleton" },
  { rank: 179, name: "Ware" },
  { rank: 180, name: "Hull" },
  { rank: 181, name: "Sturbridge" },
  { rank: 182, name: "Plainville" },
  { rank: 183, name: "Middleton" },
  { rank: 184, name: "Rutland" },
  { rank: 185, name: "Sutton" },
  { rank: 186, name: "Freetown" },
  { rank: 187, name: "Salisbury" },
  { rank: 188, name: "Douglas" },
  { rank: 189, name: "Blackstone" },
  { rank: 190, name: "Southwick" },
  { rank: 191, name: "Millis" },
  { rank: 192, name: "Lancaster" },
  { rank: 193, name: "Townsend" },
  { rank: 194, name: "Ayer" },
  { rank: 195, name: "Georgetown" },
  { rank: 196, name: "Upton" },
  { rank: 197, name: "Cohasset" },
  { rank: 198, name: "Montague" },
  { rank: 199, name: "Westminster" },
  { rank: 200, name: "Templeton" },
  { rank: 201, name: "Sterling" },
  { rank: 202, name: "Dighton" },
  { rank: 203, name: "Boxford" },
  { rank: 204, name: "Monson" },
  { rank: 205, name: "Adams" },
  { rank: 206, name: "West Boylston" },
  { rank: 207, name: "West Bridgewater" },
  { rank: 208, name: "Halifax" },
  { rank: 209, name: "Hamilton" },
  { rank: 210, name: "Orange" },
  { rank: 211, name: "Williamstown" },
  { rank: 212, name: "Great Barrington" },
  { rank: 213, name: "Stow" },
  { rank: 214, name: "Rockport" },
  { rank: 215, name: "Harvard" },
  { rank: 216, name: "Lincoln" },
  { rank: 217, name: "Shirley" },
  { rank: 218, name: "Berkley" },
  { rank: 219, name: "Newbury" },
  { rank: 220, name: "Groveland" },
  { rank: 221, name: "Merrimac" },
  { rank: 222, name: "Mattapoisett" },
  { rank: 223, name: "Chatham" },
  { rank: 224, name: "Topsfield" },
  { rank: 225, name: "Ashburnham" },
  { rank: 226, name: "Rowley" },
  { rank: 227, name: "Mendon" },
  { rank: 228, name: "Orleans" },
  { rank: 229, name: "Southampton" },
  { rank: 230, name: "Dalton" },
  { rank: 231, name: "Granby" },
  { rank: 232, name: "Hopedale" },
  { rank: 233, name: "Rochester" },
  { rank: 234, name: "Dover" },
  { rank: 235, name: "Eastham" },
  { rank: 236, name: "Bolton" },
  { rank: 237, name: "Lee" },
  { rank: 238, name: "Barre" },
  { rank: 239, name: "Boxborough" },
  { rank: 240, name: "Manchester-by-the-Sea" },
  { rank: 241, name: "Oak Bluffs" },
  { rank: 242, name: "Marion" },
  { rank: 243, name: "Hadley" },
  { rank: 244, name: "Edgartown" },
  { rank: 245, name: "Carlisle" },
  { rank: 246, name: "Deerfield" },
  { rank: 247, name: "Lenox" },
  { rank: 248, name: "Warren" },
  { rank: 249, name: "Paxton" },
  { rank: 250, name: "Boylston" },
]

interface MassachusettsCitySelectorProps {
  onCitySelect: (city: City) => void
  selectedCities: string[]
}

const MassachusettsCitySelector: React.FC<MassachusettsCitySelectorProps> = ({ onCitySelect, selectedCities }) => {
  return (
    <div className="space-y-2">
      <label htmlFor="city-select" className="block text-sm font-medium text-[#E4B649]">
        Select a Massachusetts City
      </label>
      <Select onValueChange={(value) => {
        const selectedCity = MASSACHUSETTS_CITIES.find(city => city.name === value)
        if (selectedCity) onCitySelect(selectedCity)
      }}>
        <SelectTrigger id="city-select" className="w-full bg-black/50 border-[#E4B649]/20 text-white">
          <SelectValue placeholder="Choose a city" />
        </SelectTrigger>
        <SelectContent className="bg-black border-[#E4B649]/20">
          <ScrollArea className="h-[200px]">
            {MASSACHUSETTS_CITIES.map((city) => (
              <SelectItem 
                key={city.rank} 
                value={city.name}
                className="text-white hover:bg-[#E4B649]/20"
                disabled={selectedCities.includes(city.name)}
              >
                {city.name}
              </SelectItem>
            ))}
          </ScrollArea>
        </SelectContent>
      </Select>
      <p className="text-xs text-[#E4B649]/70">
        * You can select up to 10 cities from Massachusetts
      </p>
    </div>
  )
}

export default MassachusettsCitySelector
