import React from 'react'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { ScrollArea } from "@/components/ui/scroll-area"

interface City {
  name: string
  rank: number
}

const MICHIGAN_CITIES: City[] = [
  { rank: 1, name: "Detroit" },
  { rank: 2, name: "Grand Rapids" },
  { rank: 3, name: "Warren" },
  { rank: 4, name: "Sterling Heights" },
  { rank: 5, name: "Ann Arbor" },
  { rank: 6, name: "Lansing" },
  { rank: 7, name: "Dearborn" },
  { rank: 8, name: "Clinton charter township" },
  { rank: 9, name: "Canton charter township" },
  { rank: 10, name: "Macomb township" },
  { rank: 11, name: "Livonia" },
  { rank: 12, name: "Troy" },
  { rank: 13, name: "Farmington Hills" },
  { rank: 14, name: "Westland" },
  { rank: 15, name: "Shelby charter township" },
  { rank: 16, name: "Flint" },
  { rank: 17, name: "Wyoming" },
  { rank: 18, name: "Rochester Hills" },
  { rank: 19, name: "Southfield" },
  { rank: 20, name: "Kalamazoo" },
  { rank: 21, name: "Waterford charter township" },
  { rank: 22, name: "Novi" },
  { rank: 23, name: "West Bloomfield charter township" },
  { rank: 24, name: "Pontiac" },
  { rank: 25, name: "Taylor" },
  { rank: 26, name: "Dearborn Heights" },
  { rank: 27, name: "Royal Oak" },
  { rank: 28, name: "St. Clair Shores" },
  { rank: 29, name: "Georgetown charter township" },
  { rank: 30, name: "Ypsilanti charter township" },
  { rank: 31, name: "Kentwood" },
  { rank: 32, name: "Battle Creek" },
  { rank: 33, name: "Portage" },
  { rank: 34, name: "East Lansing" },
  { rank: 35, name: "Redford charter township" },
  { rank: 36, name: "Roseville" },
  { rank: 37, name: "Chesterfield township" },
  { rank: 38, name: "Meridian charter township" },
  { rank: 39, name: "Bloomfield charter township" },
  { rank: 40, name: "Commerce charter township" },
  { rank: 41, name: "Saginaw" },
  { rank: 42, name: "Midland" },
  { rank: 43, name: "Saginaw charter township" },
  { rank: 44, name: "Holland charter township" },
  { rank: 45, name: "Grand Blanc charter township" },
  { rank: 46, name: "Pittsfield charter township" },
  { rank: 47, name: "Orion charter township" },
  { rank: 48, name: "Lincoln Park" },
  { rank: 49, name: "Independence charter township" },
  { rank: 50, name: "Muskegon" },
  { rank: 51, name: "Holland" },
  { rank: 52, name: "Plainfield charter township" },
  { rank: 53, name: "Eastpointe" },
  { rank: 54, name: "Delta charter township" },
  { rank: 55, name: "Brownstown charter township" },
  { rank: 56, name: "Bay City" },
  { rank: 57, name: "Bedford township" },
  { rank: 58, name: "White Lake charter township" },
  { rank: 59, name: "Northville township" },
  { rank: 60, name: "Flint charter township" },
  { rank: 61, name: "Jackson" },
  { rank: 62, name: "Gaines charter township" },
  { rank: 63, name: "Van Buren charter township" },
  { rank: 64, name: "Burton" },
  { rank: 65, name: "Washington charter township" },
  { rank: 66, name: "Oak Park" },
  { rank: 67, name: "Southgate" },
  { rank: 68, name: "Port Huron" },
  { rank: 69, name: "Madison Heights" },
  { rank: 70, name: "Byron township" },
  { rank: 71, name: "Delhi charter township" },
  { rank: 72, name: "Allen Park" },
  { rank: 73, name: "Hamtramck" },
  { rank: 74, name: "Allendale charter township" },
  { rank: 75, name: "Plymouth charter township" },
  { rank: 76, name: "Auburn Hills" },
  { rank: 77, name: "Garden City" },
  { rank: 78, name: "Lyon charter township" },
  { rank: 79, name: "Walker" },
  { rank: 80, name: "Blackman charter township" },
  { rank: 81, name: "Norton Shores" },
  { rank: 82, name: "Inkster" },
  { rank: 83, name: "Romulus" },
  { rank: 84, name: "Oshtemo charter township" },
  { rank: 85, name: "Harrison charter township" },
  { rank: 86, name: "Wyandotte" },
  { rank: 87, name: "Summit township" },
  { rank: 88, name: "Oxford charter township" },
  { rank: 89, name: "Kalamazoo charter township" },
  { rank: 90, name: "Frenchtown township" },
  { rank: 91, name: "Birmingham" },
  { rank: 92, name: "Marquette" },
  { rank: 93, name: "Hamburg township" },
  { rank: 94, name: "Mount Pleasant" },
  { rank: 95, name: "Genoa township" },
  { rank: 96, name: "Davison township" },
  { rank: 97, name: "Oakland charter township" },
  { rank: 98, name: "Genesee charter township" },
  { rank: 99, name: "Adrian" },
  { rank: 100, name: "Green Oak township" },
  { rank: 101, name: "Brighton township" },
  { rank: 102, name: "Garfield charter township" },
  { rank: 103, name: "Monroe" },
  { rank: 104, name: "Cascade charter township" },
  { rank: 105, name: "Grand Haven charter township" },
  { rank: 106, name: "Mount Morris township" },
  { rank: 107, name: "Park township" },
  { rank: 108, name: "Grand Rapids charter township" },
  { rank: 109, name: "Highland charter township" },
  { rank: 110, name: "Ferndale" },
  { rank: 111, name: "Ypsilanti" },
  { rank: 112, name: "Texas charter township" },
  { rank: 113, name: "Muskegon charter township" },
  { rank: 114, name: "Trenton" },
  { rank: 115, name: "Scio township" },
  { rank: 116, name: "Fenton charter township" },
  { rank: 117, name: "Wixom" },
  { rank: 118, name: "Milford charter township" },
  { rank: 119, name: "Grandville" },
  { rank: 120, name: "Wayne" },
  { rank: 121, name: "Caledonia township" },
  { rank: 122, name: "Huron charter township" },
  { rank: 123, name: "Fruitport charter township" },
  { rank: 124, name: "Traverse City" },
  { rank: 125, name: "Grosse Pointe Woods" },
  { rank: 126, name: "Spring Lake township" },
  { rank: 127, name: "Mundy township" },
  { rank: 128, name: "Hartland township" },
  { rank: 129, name: "DeWitt charter township" },
  { rank: 130, name: "Brandon charter township" },
  { rank: 131, name: "Mount Clemens" },
  { rank: 132, name: "Comstock charter township" },
  { rank: 133, name: "Superior charter township" },
  { rank: 134, name: "Lincoln charter township" },
  { rank: 135, name: "Berkley" },
  { rank: 136, name: "Springfield charter township" },
  { rank: 137, name: "Hazel Park" },
  { rank: 138, name: "Oceola township" },
  { rank: 139, name: "Harper Woods" },
  { rank: 140, name: "Coldwater" },
  { rank: 141, name: "Ada township" },
  { rank: 142, name: "Southfield township" },
  { rank: 143, name: "Owosso" },
  { rank: 144, name: "Cannon township" },
  { rank: 145, name: "Fraser" },
  { rank: 146, name: "Monroe charter township" },
  { rank: 147, name: "Niles township" },
  { rank: 148, name: "Benton charter township" },
  { rank: 149, name: "Alpine township" },
  { rank: 150, name: "Bangor charter township" },
  { rank: 151, name: "Leoni township" },
  { rank: 152, name: "Antwerp township" },
  { rank: 153, name: "Bath charter township" },
  { rank: 154, name: "Sault Ste. Marie" },
  { rank: 155, name: "Vienna charter township" },
  { rank: 156, name: "Lenox township" },
  { rank: 157, name: "Rochester" },
  { rank: 158, name: "Woodhaven" },
  { rank: 159, name: "Escanaba" },
  { rank: 160, name: "Holly township" },
  { rank: 161, name: "Algoma township" },
  { rank: 162, name: "Melvindale" },
  { rank: 163, name: "Zeeland charter township" },
  { rank: 164, name: "Marion township" },
  { rank: 165, name: "South Lyon" },
  { rank: 166, name: "New Baltimore" },
  { rank: 167, name: "Tyrone township" },
  { rank: 168, name: "Thomas township" },
  { rank: 169, name: "Ionia" },
  { rank: 170, name: "Riverview" },
  { rank: 171, name: "Fenton" },
  { rank: 172, name: "Emmett charter township" },
  { rank: 173, name: "Union charter township" },
  { rank: 174, name: "East Bay township" },
  { rank: 175, name: "Niles" },
  { rank: 176, name: "East Grand Rapids" },
  { rank: 177, name: "Fort Gratiot charter township" },
  { rank: 178, name: "Egelston township" },
  { rank: 179, name: "Farmington" },
  { rank: 180, name: "Clawson" },
  { rank: 181, name: "Grand Haven" },
  { rank: 182, name: "Grosse Pointe Park" },
  { rank: 183, name: "Sturgis" },
  { rank: 184, name: "Tittabawassee township" },
  { rank: 185, name: "Port Huron charter township" },
  { rank: 186, name: "Monitor charter township" },
  { rank: 187, name: "Flushing charter township" },
  { rank: 188, name: "Cooper charter township" },
  { rank: 189, name: "Cadillac" },
  { rank: 190, name: "Jamestown charter township" },
  { rank: 191, name: "Beverly Hills" },
  { rank: 192, name: "Grosse Ile township" },
  { rank: 193, name: "Flat Rock" },
  { rank: 194, name: "Alpena" },
  { rank: 195, name: "Long Lake township" },
  { rank: 196, name: "Howell" },
  { rank: 197, name: "Marysville" },
  { rank: 198, name: "Berlin charter township" },
  { rank: 199, name: "Bridgeport charter township" },
  { rank: 200, name: "Bruce township" },
  { rank: 201, name: "Muskegon Heights" },
  { rank: 202, name: "St. Joseph charter township" },
  { rank: 203, name: "Thornapple township" },
  { rank: 204, name: "Grosse Pointe Farms" },
  { rank: 205, name: "Dalton township" },
  { rank: 206, name: "Kimball township" },
  { rank: 207, name: "Hampton charter township" },
  { rank: 208, name: "Sparta township" },
  { rank: 209, name: "Sumpter township" },
  { rank: 210, name: "Schoolcraft township" },
  { rank: 211, name: "Alma" },
  { rank: 212, name: "Charlotte" },
  { rank: 213, name: "Blair township" },
  { rank: 214, name: "Tallmadge charter township" },
  { rank: 215, name: "Bedford charter township" },
  { rank: 216, name: "Lapeer" },
  { rank: 217, name: "Alpena township" },
  { rank: 218, name: "Courtland township" },
  { rank: 219, name: "Plymouth" },
  { rank: 220, name: "York charter township" },
  { rank: 221, name: "Richland township" },
  { rank: 222, name: "Greenville" },
  { rank: 223, name: "Saline" },
  { rank: 224, name: "Oronoko charter township" },
  { rank: 225, name: "Richfield township" },
  { rank: 226, name: "Handy township" },
  { rank: 227, name: "Ecorse" },
  { rank: 228, name: "Benton Harbor" },
  { rank: 229, name: "Dundee township" },
  { rank: 230, name: "Pennfield charter township" },
  { rank: 231, name: "Howell township" },
  { rank: 232, name: "Tecumseh" },
  { rank: 233, name: "Houghton" },
  { rank: 234, name: "Spring Arbor township" },
  { rank: 235, name: "Northfield township" },
  { rank: 236, name: "Center Line" },
  { rank: 237, name: "Atlas township" },
  { rank: 238, name: "Clay township" },
  { rank: 239, name: "Highland Park" },
  { rank: 240, name: "Flushing" },
  { rank: 241, name: "Brighton" },
  { rank: 242, name: "Menominee" },
  { rank: 243, name: "Mason" },
  { rank: 244, name: "Mayfield township" },
  { rank: 245, name: "Raisin township" },
  { rank: 246, name: "Hillsdale" },
  { rank: 247, name: "Big Rapids" },
  { rank: 248, name: "Hudsonville" },
  { rank: 249, name: "Dorr township" },
  { rank: 250, name: "Lansing charter township" },
  { rank: 251, name: "Ash township" },
  { rank: 252, name: "Three Rivers" },
  { rank: 253, name: "Grand Blanc" },
  { rank: 254, name: "Grand Ledge" },
  { rank: 255, name: "Putnam township" },
  { rank: 256, name: "St. Johns" },
  { rank: 257, name: "St. Joseph" },
  { rank: 258, name: "Laketon township" },
  { rank: 259, name: "Ludington" },
  { rank: 260, name: "Blendon township" },
  { rank: 261, name: "Iron Mountain" },
  { rank: 262, name: "Hastings" },
  { rank: 263, name: "Buena Vista charter township" },
  { rank: 264, name: "Columbia township" },
  { rank: 265, name: "Clayton charter township" },
  { rank: 266, name: "Walled Lake" },
  { rank: 267, name: "Albion" },
  { rank: 268, name: "Leighton township" },
  { rank: 269, name: "Oscoda charter township" },
  { rank: 270, name: "St. Clair township" },
  { rank: 271, name: "Windsor charter township" },
  { rank: 272, name: "Almont township" },
  { rank: 273, name: "Madison charter township" },
  { rank: 274, name: "St. Louis" },
  { rank: 275, name: "Argentine township" },
  { rank: 276, name: "Augusta charter township" },
  { rank: 277, name: "Salem township" },
  { rank: 278, name: "Paw Paw township" },
  { rank: 279, name: "Bloomer township" },
  { rank: 280, name: "Ontwa township" },
  { rank: 281, name: "New Haven" },
  { rank: 282, name: "Green Lake township" },
  { rank: 283, name: "River Rouge" },
  { rank: 284, name: "Marshall" },
  { rank: 285, name: "Napoleon township" },
  { rank: 286, name: "Kinross charter township" },
  { rank: 287, name: "Gaines township" },
  { rank: 288, name: "Bear Creek township" },
  { rank: 289, name: "Dexter township" },
  { rank: 290, name: "Solon township" },
  { rank: 291, name: "Webster township" },
  { rank: 292, name: "Thetford township" },
  { rank: 293, name: "Robinson township" },
  { rank: 294, name: "Milford" },
  { rank: 295, name: "Lowell charter township" },
  { rank: 296, name: "Pavilion township" },
  { rank: 297, name: "Forsyth township" },
  { rank: 298, name: "Adrian township" },
  { rank: 299, name: "Manistee" },
  { rank: 300, name: "Lodi township" },
  { rank: 301, name: "Calumet charter township" },
  { rank: 302, name: "Howard township" },
  { rank: 303, name: "Laketown township" },
  { rank: 304, name: "Huntington Woods" },
  { rank: 305, name: "Addison township" },
  { rank: 306, name: "Grass Lake charter township" },
  { rank: 307, name: "Ishpeming" },
  { rank: 308, name: "Gun Plain township" },
  { rank: 309, name: "Rockford" },
  { rank: 310, name: "Dundee" },
  { rank: 311, name: "Rose township" },
  { rank: 312, name: "Peninsula township" },
  { rank: 313, name: "Boston township" },
  { rank: 314, name: "Bagley township" },
  { rank: 315, name: "Oakfield township" },
  { rank: 316, name: "Otsego township" },
  { rank: 317, name: "Chocolay charter township" },
  { rank: 318, name: "St. Clair" },
  { rank: 319, name: "Raisinville township" },
  { rank: 320, name: "Milan" },
  { rank: 321, name: "Belding" },
  { rank: 322, name: "Northville" },
  { rank: 323, name: "Montrose charter township" },
  { rank: 324, name: "Groveland township" },
  { rank: 325, name: "Holly" },
  { rank: 326, name: "Fruitland township" },
  { rank: 327, name: "Breitung charter township" },
  { rank: 328, name: "Petoskey" },
  { rank: 329, name: "Swartz Creek" },
  { rank: 330, name: "Richmond" },
  { rank: 331, name: "Birch Run township" },
  { rank: 332, name: "Watertown charter township" },
  { rank: 333, name: "Grayling charter township" },
  { rank: 334, name: "Deerfield township" },
  { rank: 335, name: "Cambridge township" },
  { rank: 336, name: "Oregon township" },
  { rank: 337, name: "Reynolds township" },
  { rank: 338, name: "Dowagiac" },
  { rank: 339, name: "Zeeland" },
  { rank: 340, name: "Port Sheldon township" },
  { rank: 341, name: "Carrollton township" },
  { rank: 342, name: "Yankee Springs township" },
  { rank: 343, name: "Larkin charter township" },
  { rank: 344, name: "Clyde township" },
  { rank: 345, name: "Denton township" },
  { rank: 346, name: "Almena township" },
  { rank: 347, name: "Grosse Pointe" },
  { rank: 348, name: "Chelsea" },
  { rank: 349, name: "Armada township" },
  { rank: 350, name: "Olive township" },
  { rank: 351, name: "Springfield" },
  { rank: 352, name: "Williamstown township" },
  { rank: 353, name: "Elba township" },
  { rank: 354, name: "Gladstone" },
  { rank: 355, name: "Kalkaska township" },
  { rank: 356, name: "Frankenmuth" },
  { rank: 357, name: "Salem township" },
  { rank: 358, name: "Tyrone township" },
  { rank: 359, name: "Eaton Rapids" },
  { rank: 360, name: "Allegan" },
  { rank: 361, name: "Kingsford" },
  { rank: 362, name: "Royalton township" },
  { rank: 363, name: "Utica" },
  { rank: 364, name: "Elmwood charter township" },
  { rank: 365, name: "Paradise township" },
  { rank: 366, name: "Davison" },
  { rank: 367, name: "Kochville township" },
  { rank: 368, name: "Williams charter township" },
  { rank: 369, name: "Fort Gratiot township" }
]

interface MichiganCitySelectorProps {
  onCitySelect: (city: City) => void
  selectedCities: string[]
}

const MichiganCitySelector: React.FC<MichiganCitySelectorProps> = ({ onCitySelect, selectedCities }) => {
  return (
    <div className="space-y-2">
      <label htmlFor="city-select" className="block text-sm font-medium text-[#E4B649]">
        Select a Michigan City
      </label>
      <Select onValueChange={(value) => {
        const selectedCity = MICHIGAN_CITIES.find(city => city.name === value)
        if (selectedCity) onCitySelect(selectedCity)
      }}>
        <SelectTrigger id="city-select" className="w-full bg-black/50 border-[#E4B649]/20 text-white">
          <SelectValue placeholder="Choose a city" />
        </SelectTrigger>
        <SelectContent className="bg-black border-[#E4B649]/20">
          <ScrollArea className="h-[200px]">
            {MICHIGAN_CITIES.map((city) => (
              <SelectItem 
                key={city.rank} 
                value={city.name}
                className="text-white hover:bg-[#E4B649]/20"
                disabled={selectedCities.includes(city.name)}
              >
                {city.name}
              </SelectItem>
            ))}
          </ScrollArea>
        </SelectContent>
      </Select>
      <p className="text-xs text-[#E4B649]/70">
        * You can select up to 10 cities from Michigan
      </p>
    </div>
  )
}

export default MichiganCitySelector

