import React from 'react'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { ScrollArea } from "@/components/ui/scroll-area"

interface City {
  name: string
  rank: number
}

const NEW_YORK_CITIES: City[] = [
  { rank: 1, name: "New York City" },
  { rank: 2, name: "Hempstead" },
  { rank: 3, name: "Brookhaven" },
  { rank: 4, name: "Islip" },
  { rank: 5, name: "Oyster Bay" },
  { rank: 6, name: "Buffalo" },
  { rank: 7, name: "North Hempstead" },
  { rank: 8, name: "Babylon" },
  { rank: 9, name: "Yonkers" },
  { rank: 10, name: "Rochester" },
  { rank: 11, name: "Huntington" },
  { rank: 12, name: "Ramapo" },
  { rank: 13, name: "Syracuse" },
  { rank: 14, name: "Amherst" },
  { rank: 15, name: "Smithtown" },
  { rank: 16, name: "Albany" },
  { rank: 17, name: "Greece" },
  { rank: 18, name: "Greenburgh" },
  { rank: 19, name: "Cheektowaga" },
  { rank: 20, name: "Clarkstown" },
  { rank: 21, name: "Colonie" },
  { rank: 22, name: "New Rochelle" },
  { rank: 23, name: "Tonawanda" },
  { rank: 24, name: "Mount Vernon" },
  { rank: 25, name: "Southampton" },
  { rank: 26, name: "Schenectady" },
  { rank: 27, name: "Utica" },
  { rank: 28, name: "White Plains" },
  { rank: 29, name: "Hamburg" },
  { rank: 30, name: "Clay" },
  { rank: 31, name: "Hempstead" },
  { rank: 32, name: "Union" },
  { rank: 33, name: "Troy" },
  { rank: 34, name: "Henrietta" },
  { rank: 35, name: "Irondequoit" },
  { rank: 36, name: "Orangetown" },
  { rank: 37, name: "Rye" },
  { rank: 38, name: "Niagara Falls" },
  { rank: 39, name: "Perinton" },
  { rank: 40, name: "Binghamton" },
  { rank: 41, name: "Poughkeepsie" },
  { rank: 42, name: "Lancaster" },
  { rank: 43, name: "Webster" },
  { rank: 44, name: "West Seneca" },
  { rank: 45, name: "Palm Tree" },
  { rank: 46, name: "Kiryas Joel" },
  { rank: 47, name: "Mount Pleasant" },
  { rank: 48, name: "Freeport" },
  { rank: 49, name: "Cortlandt" },
  { rank: 50, name: "Valley Stream" },
  { rank: 51, name: "Haverstraw" },
  { rank: 52, name: "Ossining" },
  { rank: 53, name: "Penfield" },
  { rank: 54, name: "Clifton Park" },
  { rank: 55, name: "Guilderland" },
  { rank: 56, name: "Brighton" },
  { rank: 57, name: "Riverhead" },
  { rank: 58, name: "Bethlehem" },
  { rank: 59, name: "Yorktown" },
  { rank: 60, name: "Long Beach" },
  { rank: 61, name: "Carmel" },
  { rank: 62, name: "Ithaca" },
  { rank: 63, name: "Eastchester" },
  { rank: 64, name: "Clarence" },
  { rank: 65, name: "Spring Valley" },
  { rank: 66, name: "Manlius" },
  { rank: 67, name: "Salina" },
  { rank: 68, name: "Harrison" },
  { rank: 69, name: "Poughkeepsie" },
  { rank: 70, name: "Vestal" },
  { rank: 71, name: "Harrison" },
  { rank: 72, name: "Newburgh" },
  { rank: 73, name: "Rome" },
  { rank: 74, name: "Warwick" },
  { rank: 75, name: "Wallkill" },
  { rank: 76, name: "Cicero" },
  { rank: 77, name: "Rotterdam" },
  { rank: 78, name: "Mamaroneck" },
  { rank: 79, name: "Port Chester" },
  { rank: 80, name: "Pittsford" },
  { rank: 81, name: "Middletown" },
  { rank: 82, name: "North Tonawanda" },
  { rank: 83, name: "Orchard Park" },
  { rank: 84, name: "East Fishkill" },
  { rank: 85, name: "Glenville" },
  { rank: 86, name: "Queensbury" },
  { rank: 87, name: "East Hampton" },
  { rank: 88, name: "Chili" },
  { rank: 89, name: "Gates" },
  { rank: 90, name: "Saratoga Springs" },
  { rank: 91, name: "Newburgh" },
  { rank: 92, name: "Wappinger" },
  { rank: 93, name: "Glen Cove" },
  { rank: 94, name: "Jamestown" },
  { rank: 95, name: "New Windsor" },
  { rank: 96, name: "Lindenhurst" },
  { rank: 97, name: "Halfmoon" },
  { rank: 98, name: "Ossining" },
  { rank: 99, name: "Elmira" },
  { rank: 100, name: "Auburn" },
  { rank: 101, name: "Le Ray" },
  { rank: 102, name: "Peekskill" },
  { rank: 103, name: "Rockville Centre" },
  { rank: 104, name: "Camillus" },
  { rank: 105, name: "De Witt" },
  { rank: 106, name: "Watertown" },
  { rank: 107, name: "Southold" },
  { rank: 108, name: "Niskayuna" },
  { rank: 109, name: "Kingston" },
  { rank: 110, name: "Montgomery" },
  { rank: 111, name: "Lysander" },
  { rank: 112, name: "Garden City" },
  { rank: 113, name: "Fishkill" },
  { rank: 114, name: "Onondaga" },
  { rank: 115, name: "New Hartford" },
  { rank: 116, name: "Grand Island" },
  { rank: 117, name: "Mineola" },
  { rank: 118, name: "Hyde Park" },
  { rank: 119, name: "Monroe" },
  { rank: 120, name: "Ithaca" },
  { rank: 121, name: "Somers" },
  { rank: 122, name: "Lockport" },
  { rank: 123, name: "Lockport" },
  { rank: 124, name: "Ogden" },
  { rank: 125, name: "Lynbrook" },
  { rank: 126, name: "Milton" },
  { rank: 127, name: "Plattsburgh" },
  { rank: 128, name: "Saugerties" },
  { rank: 129, name: "Lackawanna" },
  { rank: 130, name: "Mamaroneck" },
  { rank: 131, name: "Owego" },
  { rank: 132, name: "Horseheads" },
  { rank: 133, name: "Wheatfield" },
  { rank: 134, name: "Blooming Grove" },
  { rank: 135, name: "Cohoes" },
  { rank: 136, name: "Southeast" },
  { rank: 137, name: "Amsterdam" },
  { rank: 138, name: "Whitestown" },
  { rank: 139, name: "Scarsdale" },
  { rank: 140, name: "New Castle" },
  { rank: 141, name: "Scarsdale" },
  { rank: 142, name: "Malta" },
  { rank: 143, name: "Wilton" },
  { rank: 144, name: "Cortland" },
  { rank: 145, name: "Oswego" },
  { rank: 146, name: "Massapequa Park" },
  { rank: 147, name: "Geddes" },
  { rank: 148, name: "Moreau" },
  { rank: 149, name: "Thompson" },
  { rank: 150, name: "East Greenbush" },
  { rank: 151, name: "LaGrange" },
  { rank: 152, name: "Bedford" },
  { rank: 153, name: "Victor" },
  { rank: 154, name: "Rye" },
  { rank: 155, name: "Oneonta" },
  { rank: 156, name: "Parma" },
  { rank: 157, name: "Floral Park" },
  { rank: 158, name: "Westbury" },
  { rank: 159, name: "Lewiston" },
  { rank: 160, name: "New Paltz" },
  { rank: 161, name: "Batavia" },
  { rank: 162, name: "Beacon" },
  { rank: 163, name: "Evans" },
  { rank: 164, name: "Fallsburg" },
  { rank: 165, name: "Farmington" },
  { rank: 166, name: "Kenmore" },
  { rank: 167, name: "Tonawanda" },
  { rank: 168, name: "Depew" },
  { rank: 169, name: "Potsdam" },
  { rank: 170, name: "Gloversville" },
  { rank: 171, name: "Johnson City" },
  { rank: 172, name: "Stony Point" },
  { rank: 173, name: "Sullivan" },
  { rank: 174, name: "Glens Falls" },
  { rank: 175, name: "Goshen" },
  { rank: 176, name: "Beekman" },
  { rank: 177, name: "Van Buren" },
  { rank: 178, name: "Aurora" },
  { rank: 179, name: "Olean" },
  { rank: 180, name: "Arcadia" },
  { rank: 181, name: "Shawangunk" },
  { rank: 182, name: "Sweden" },
  { rank: 183, name: "North Greenbush" },
  { rank: 184, name: "Dryden" },
  { rank: 185, name: "Endicott" },
  { rank: 186, name: "Schodack" },
  { rank: 187, name: "Kingsbury" },
  { rank: 188, name: "Kent" },
  { rank: 189, name: "Ballston" },
  { rank: 190, name: "Highlands" },
  { rank: 191, name: "Pomfret" },
  { rank: 192, name: "Mamakating" },
  { rank: 193, name: "Chester" },
  { rank: 194, name: "Pelham" },
  { rank: 195, name: "Cornwall" },
  { rank: 196, name: "Wawarsing" },
  { rank: 197, name: "Ulster" },
  { rank: 198, name: "Brunswick" },
  { rank: 199, name: "Dunkirk" },
  { rank: 200, name: "Patchogue" },
  { rank: 201, name: "Geneva" },
  { rank: 202, name: "Haverstraw" },
  { rank: 203, name: "Massena" },
  { rank: 204, name: "Woodbury" },
  { rank: 205, name: "Babylon" },
  { rank: 206, name: "German Flatts" },
  { rank: 207, name: "North Castle" },
  { rank: 208, name: "Lewisboro" },
  { rank: 209, name: "Plattsburgh" },
  { rank: 210, name: "Tarrytown" },
  { rank: 211, name: "Putnam Valley" },
  { rank: 212, name: "Malone" },
  { rank: 213, name: "Elma" },
  { rank: 214, name: "Lansing" },
  { rank: 215, name: "Canandaigua" },
  { rank: 216, name: "Woodbury" },
  { rank: 217, name: "Patterson" },
  { rank: 218, name: "Canton" },
  { rank: 219, name: "Suffern" },
  { rank: 220, name: "Sleepy Hollow" },
  { rank: 221, name: "Bath" },
  { rank: 222, name: "Dobbs Ferry" },
  { rank: 223, name: "Catskill" },
  { rank: 224, name: "Fulton" },
  { rank: 225, name: "Red Hook" },
  { rank: 226, name: "Lloyd" },
  { rank: 227, name: "Lake Grove" },
  { rank: 228, name: "Great Neck" },
  { rank: 229, name: "Corning" },
  { rank: 230, name: "West Haverstraw" },
  { rank: 231, name: "Chenango" },
  { rank: 232, name: "Chestnut Ridge" },
  { rank: 233, name: "Ontario" },
  { rank: 234, name: "Mount Kisco" },
  { rank: 235, name: "Canandaigua" },
  { rank: 236, name: "Mount Kisco" },
  { rank: 237, name: "Geneseo" },
  { rank: 238, name: "Liberty" },
  { rank: 239, name: "Plattekill" },
  { rank: 240, name: "Airmont" },
  { rank: 241, name: "Watervliet" },
  { rank: 242, name: "New Hyde Park" },
  { rank: 243, name: "Alden" },
  { rank: 244, name: "Massena" },
  { rank: 245, name: "Oneida" },
  { rank: 246, name: "Lancaster" },
  { rank: 247, name: "East Rockaway" },
  { rank: 248, name: "New Square" },
  { rank: 249, name: "Philipstown" },
  { rank: 250, name: "Hamburg" },
  { rank: 251, name: "Pleasant Valley" },
  { rank: 252, name: "Rye Brook" },
  { rank: 253, name: "Kirkland" },
  { rank: 254, name: "Amityville" },
  { rank: 255, name: "Stillwater" },
  { rank: 256, name: "Esopus" },
  { rank: 257, name: "Monroe" },
  { rank: 258, name: "Herkimer" },
  { rank: 259, name: "Walworth" },
  { rank: 260, name: "Fredonia" },
  { rank: 261, name: "Hastings" },
  { rank: 262, name: "Rensselaer" },
  { rank: 263, name: "Macedon" },
  { rank: 264, name: "Manchester" },
  { rank: 265, name: "Newfane" },
  { rank: 266, name: "New Scotland" },
  { rank: 267, name: "Ogdensburg" },
  { rank: 268, name: "Mendon" },
  { rank: 269, name: "Crawford" },
  { rank: 270, name: "New Paltz" },
  { rank: 271, name: "Newark" },
  { rank: 272, name: "Southport" },
  { rank: 273, name: "Marlborough" },
  { rank: 274, name: "Seneca Falls" },
  { rank: 275, name: "Newstead" },
  { rank: 276, name: "Oswego" },
  { rank: 277, name: "Lenox" },
  { rank: 278, name: "Ellicott" },
  { rank: 279, name: "Hamlin" },
  { rank: 280, name: "Farmingdale" },
  { rank: 281, name: "Port Jervis" },
  { rank: 282, name: "Potsdam" },
  { rank: 283, name: "Malverne" },
  { rank: 284, name: "Barton" },
  { rank: 285, name: "Marcy" },
  { rank: 286, name: "Dover" },
  { rank: 287, name: "Sand Lake" },
  { rank: 288, name: "Hastings-on-Hudson" },
  { rank: 289, name: "Concord" },
  { rank: 290, name: "Port Jefferson" },
  { rank: 291, name: "Cortlandville" },
  { rank: 292, name: "Croton-on-Hudson" },
  { rank: 293, name: "Vernon" },
  { rank: 294, name: "Johnstown" },
  { rank: 295, name: "Pawling" },
  { rank: 296, name: "Sodus" },
  { rank: 297, name: "Waterford" },
  { rank: 298, name: "Kinderhook" },
  { rank: 299, name: "Greenfield" },
  { rank: 300, name: "Hornell" },
  { rank: 301, name: "Schroeppel" },
  { rank: 302, name: "Boston" },
  { rank: 303, name: "Erwin" },
  { rank: 304, name: "Geneseo" },
  { rank: 305, name: "Great Neck Plaza" },
  { rank: 306, name: "North Elba" },
  { rank: 307, name: "Niagara" },
  { rank: 308, name: "Baldwinsville" },
  { rank: 309, name: "Colonie" },
  { rank: 310, name: "Le Roy" },
  { rank: 311, name: "Ilion" },
  { rank: 312, name: "Coxsackie" },
  { rank: 313, name: "Eden" },
  { rank: 314, name: "Rhinebeck" },
  { rank: 315, name: "Big Flats" },
  { rank: 316, name: "Williston Park" },
  { rank: 317, name: "Royalton" },
  { rank: 318, name: "Livonia" },
  { rank: 319, name: "Wawayanda" },
  { rank: 320, name: "Busti" },
  { rank: 321, name: "Rochester" },
  { rank: 322, name: "Hudson Falls" },
  { rank: 323, name: "Allegany" },
  { rank: 324, name: "Deerpark" },
  { rank: 325, name: "Palmyra" },
  { rank: 326, name: "Schaghticoke" },
  { rank: 327, name: "Cedarhurst" },
  { rank: 328, name: "Northport" },
  { rank: 329, name: "Briarcliff Manor" },
  { rank: 330, name: "Nyack" },
  { rank: 331, name: "Waterloo" },
  { rank: 332, name: "East Hills" },
  { rank: 333, name: "Herkimer" },
  { rank: 334, name: "Monticello" },
  { rank: 335, name: "Scotia" },
  { rank: 336, name: "Coeymans" },
  { rank: 337, name: "Pleasantville" },
  { rank: 338, name: "Brockport" },
  { rank: 339, name: "Pelham" },
  { rank: 340, name: "Skaneateles" },
  { rank: 341, name: "Pendleton" },
  { rank: 342, name: "Pompey" },
  { rank: 343, name: "Avon" },
  { rank: 344, name: "Canton" },
  { rank: 345, name: "Walden" },
  { rank: 346, name: "Albion" },
  { rank: 347, name: "Wellsville" },
  { rank: 348, name: "Manorhaven" },
  { rank: 349, name: "Frankfort" },
  { rank: 350, name: "Tuckahoe" },
  { rank: 351, name: "Milo" },
  { rank: 352, name: "Hanover" },
  { rank: 353, name: "Williamson" },
  { rank: 354, name: "North Syracuse" },
  { rank: 355, name: "Clarkson" },
  { rank: 356, name: "Lawrence" },
  { rank: 357, name: "Corinth" },
  { rank: 358, name: "Cazenovia" },
  { rank: 359, name: "Bayville" },
  { rank: 360, name: "Peru" },
  { rank: 361, name: "Scriba" },
  { rank: 362, name: "Cairo" },
  { rank: 363, name: "Hoosick" },
  { rank: 364, name: "Norwich" },
  { rank: 365, name: "Gouverneur" },
  { rank: 366, name: "Elmira" },
  { rank: 367, name: "Phelps" },
  { rank: 368, name: "Granby" },
  { rank: 369, name: "Warwick" },
  { rank: 370, name: "Larchmont" },
  { rank: 371, name: "Solvay" },
  { rank: 372, name: "Ridgeway" },
  { rank: 373, name: "Porter" },
  { rank: 374, name: "Mount Hope" },
  { rank: 375, name: "Hamilton" },
  { rank: 376, name: "Irvington" },
  { rank: 377, name: "Johnstown" },
  { rank: 378, name: "Bronxville" },
  { rank: 379, name: "Cobleskill" },
  { rank: 380, name: "Horseheads" },
  { rank: 381, name: "Batavia" },
  { rank: 382, name: "Woodstock" },
  { rank: 383, name: "Wesley Hills" },
  { rank: 384, name: "Fenton" },
  { rank: 385, name: "Granville" },
  { rank: 386, name: "East Rochester" },
  { rank: 387, name: "Hurley" },
  { rank: 388, name: "East Rochester" },
  { rank: 389, name: "Mayfield" },
  { rank: 390, name: "Homer" },
  { rank: 391, name: "Wappingers Falls" },
  { rank: 392, name: "Lee" },
  { rank: 393, name: "Claverack" },
  { rank: 394, name: "East Aurora" },
  { rank: 395, name: "Marcellus" },
  { rank: 396, name: "Alfred" },
  { rank: 397, name: "Duanesburg" },
  { rank: 398, name: "Fort Edward" },
  { rank: 399, name: "Medina" },
  { rank: 400, name: "Westmoreland" },
  { rank: 401, name: "Hilton" },
  { rank: 402, name: "Verona" },
  { rank: 403, name: "Saratoga" },
  { rank: 404, name: "Kaser" },
  { rank: 405, name: "Corning" },
  { rank: 406, name: "Brownville" },
  { rank: 407, name: "Albion" },
  { rank: 408, name: "Webster" },
  { rank: 409, name: "Hudson" },
  { rank: 410, name: "Salamanca" },
  { rank: 411, name: "Richland" },
  { rank: 412, name: "Goshen" },
  { rank: 413, name: "Perry" },
  { rank: 414, name: "Wilson" },
  { rank: 415, name: "Cambria" },
  { rank: 416, name: "Marbletown" },
  { rank: 417, name: "Rosendale" },
  { rank: 418, name: "Volney" },
  { rank: 419, name: "Amsterdam" },
  { rank: 420, name: "Champlain" },
  { rank: 421, name: "Washingtonville" },
  { rank: 422, name: "Kings Point" },
  { rank: 423, name: "Gardiner" },
  { rank: 424, name: "Wilna" },
  { rank: 425, name: "Windsor" },
  { rank: 426, name: "Riga" },
  { rank: 427, name: "Lyons" },
  { rank: 428, name: "Bath" },
  { rank: 429, name: "Hamptonburgh" },
  { rank: 430, name: "Pelham Manor" },
  { rank: 431, name: "Williamsville" },
  { rank: 432, name: "Watertown" },
  { rank: 433, name: "Groton" },
  { rank: 434, name: "Sidney" },
  { rank: 435, name: "Pittstown" },
  { rank: 436, name: "New Hempstead" },
  { rank: 437, name: "Beekmantown" },
  { rank: 438, name: "Elbridge" },
  { rank: 439, name: "Malone" },
  { rank: 440, name: "North Hills" },
  { rank: 441, name: "Fairport" },
  { rank: 442, name: "Mexico" },
  { rank: 443, name: "Kirkwood" },
  { rank: 444, name: "Warsaw" },
  { rank: 445, name: "Harrietstown" },
  { rank: 446, name: "Ghent" },
  { rank: 447, name: "Attica" },
  { rank: 448, name: "Delhi" },
  { rank: 449, name: "North Dansville" },
  { rank: 450, name: "Liberty" },
  { rank: 451, name: "Walton" },
  { rank: 452, name: "Marilla" },
  { rank: 453, name: "Northumberland" },
  { rank: 454, name: "Vienna" },
  { rank: 455, name: "Broadalbin" },
  { rank: 456, name: "North Salem" },
  { rank: 457, name: "Tupper Lake" },
  { rank: 458, name: "Mechanicville" },
  { rank: 459, name: "Elmsford" },
  { rank: 460, name: "Penn Yan" },
  { rank: 461, name: "Old Westbury" },
  { rank: 462, name: "Greene" }
]

interface NewYorkCitySelectorProps {
  onCitySelect: (city: City) => void
  selectedCities: string[]
}

const NewYorkCitySelector: React.FC<NewYorkCitySelectorProps> = ({ onCitySelect, selectedCities }) => {
  return (
    <div className="space-y-2">
      <label htmlFor="city-select" className="block text-sm font-medium text-[#E4B649]">
        Select a New York City
      </label>
      <Select onValueChange={(value) => {
        const selectedCity = NEW_YORK_CITIES.find(city => city.name === value)
        if (selectedCity) onCitySelect(selectedCity)
      }}>
        <SelectTrigger id="city-select" className="w-full bg-black/50 border-[#E4B649]/20 text-white">
          <SelectValue placeholder="Choose a city" />
        </SelectTrigger>
        <SelectContent className="bg-black border-[#E4B649]/20">
          <ScrollArea className="h-[200px]">
            {NEW_YORK_CITIES.map((city) => (
              <SelectItem 
                key={city.rank} 
                value={city.name}
                className="text-white hover:bg-[#E4B649]/20"
                disabled={selectedCities.includes(city.name)}
              >
                {city.name}
              </SelectItem>
            ))}
          </ScrollArea>
        </SelectContent>
      </Select>
      <p className="text-xs text-[#E4B649]/70">
        * You can select up to 10 cities from New York
      </p>
    </div>
  )
}

export default NewYorkCitySelector
