import React from 'react'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { ScrollArea } from "@/components/ui/scroll-area"

interface City {
  name: string
  rank: number
}

const PENNSYLVANIA_CITIES: City[] = [
  { rank: 1, name: "Philadelphia" },
  { rank: 2, name: "Pittsburgh" },
  { rank: 3, name: "Allentown" },
  { rank: 4, name: "Reading" },
  { rank: 5, name: "Erie" },
  { rank: 6, name: "Upper Darby township" },
  { rank: 7, name: "Bethlehem" },
  { rank: 8, name: "Scranton" },
  { rank: 9, name: "Lower Merion township" },
  { rank: 10, name: "Bensalem township" },
  { rank: 11, name: "Abington township" },
  { rank: 12, name: "Lancaster" },
  { rank: 13, name: "Lower Paxton township" },
  { rank: 14, name: "Bristol township" },
  { rank: 15, name: "Millcreek township" },
  { rank: 16, name: "Haverford township" },
  { rank: 17, name: "Harrisburg" },
  { rank: 18, name: "Middletown township" },
  { rank: 19, name: "York" },
  { rank: 20, name: "Manheim township" },
  { rank: 21, name: "Wilkes-Barre" },
  { rank: 22, name: "Altoona" },
  { rank: 23, name: "Hempfield township" },
  { rank: 24, name: "State College" },
  { rank: 25, name: "Northampton township" },
  { rank: 26, name: "Penn Hills township" },
  { rank: 27, name: "Cheltenham township" },
  { rank: 28, name: "Upper Merion township" },
  { rank: 29, name: "Hampden township" },
  { rank: 30, name: "Norristown" },
  { rank: 31, name: "Cranberry township" },
  { rank: 32, name: "Falls township" },
  { rank: 33, name: "Chester" },
  { rank: 34, name: "Radnor township" },
  { rank: 35, name: "Lower Makefield township" },
  { rank: 36, name: "Warminster township" },
  { rank: 37, name: "Mount Lebanon township" },
  { rank: 38, name: "Lower Macungie township" },
  { rank: 39, name: "Ross township" },
  { rank: 40, name: "Bethel Park" },
  { rank: 41, name: "North Huntingdon township" },
  { rank: 42, name: "Tredyffrin township" },
  { rank: 43, name: "Ridley township" },
  { rank: 44, name: "York township" },
  { rank: 45, name: "Hazleton" },
  { rank: 46, name: "Easton" },
  { rank: 47, name: "Upper Macungie township" },
  { rank: 48, name: "Whitehall township" },
  { rank: 49, name: "Spring township" },
  { rank: 50, name: "McCandless township" },
  { rank: 51, name: "Susquehanna township" },
  { rank: 52, name: "Springettsbury township" },
  { rank: 53, name: "Monroeville" },
  { rank: 54, name: "Swatara township" },
  { rank: 55, name: "Horsham township" },
  { rank: 56, name: "Williamsport" },
  { rank: 57, name: "Upper Dublin township" },
  { rank: 58, name: "East Hempfield township" },
  { rank: 59, name: "Shaler township" },
  { rank: 60, name: "Bethlehem township" },
  { rank: 61, name: "Moon township" },
  { rank: 62, name: "Warrington township" },
  { rank: 63, name: "Lebanon" },
  { rank: 64, name: "Plum" },
  { rank: 65, name: "Upper Moreland township" },
  { rank: 66, name: "Montgomery township" },
  { rank: 67, name: "Lower Providence township" },
  { rank: 68, name: "Exeter township" },
  { rank: 69, name: "Upper Providence township" },
  { rank: 70, name: "Derry township" },
  { rank: 71, name: "Springfield township" },
  { rank: 72, name: "Upper Allen township" },
  { rank: 73, name: "Marple township" },
  { rank: 74, name: "West Goshen township" },
  { rank: 75, name: "Dover township" },
  { rank: 76, name: "Pottstown" },
  { rank: 77, name: "Peters township" },
  { rank: 78, name: "Carlisle" },
  { rank: 79, name: "Chambersburg" },
  { rank: 80, name: "Palmer township" },
  { rank: 81, name: "Muhlenberg township" },
  { rank: 82, name: "Manor township" },
  { rank: 83, name: "South Whitehall township" },
  { rank: 84, name: "Limerick township" },
  { rank: 85, name: "Silver Spring township" },
  { rank: 86, name: "New Castle" },
  { rank: 87, name: "Unity township" },
  { rank: 88, name: "East Pennsboro township" },
  { rank: 89, name: "West Whiteland township" },
  { rank: 90, name: "Springfield township" },
  { rank: 91, name: "Buckingham township" },
  { rank: 92, name: "Penn township" },
  { rank: 93, name: "Murrysville" },
  { rank: 94, name: "Baldwin" },
  { rank: 95, name: "Whitpain township" },
  { rank: 96, name: "Coolbaugh township" },
  { rank: 97, name: "Upper St. Clair township" },
  { rank: 98, name: "Lower Southampton township" },
  { rank: 99, name: "Phoenixville" },
  { rank: 100, name: "West Chester" },
  { rank: 101, name: "Whitemarsh township" },
  { rank: 102, name: "Manchester township" },
  { rank: 103, name: "Uwchlan township" },
  { rank: 104, name: "Lower Allen township" },
  { rank: 105, name: "Newtown township" },
  { rank: 106, name: "Hatfield township" },
  { rank: 107, name: "Stroud township" },
  { rank: 108, name: "Warwick township" },
  { rank: 109, name: "West Manchester township" },
  { rank: 110, name: "Lansdale" },
  { rank: 111, name: "Lancaster township" },
  { rank: 112, name: "Ferguson township" },
  { rank: 113, name: "West Mifflin" },
  { rank: 114, name: "Greene township" },
  { rank: 115, name: "Plymouth township" },
  { rank: 116, name: "South Fayette township" },
  { rank: 117, name: "Penn township" },
  { rank: 118, name: "East Goshen township" },
  { rank: 119, name: "Concord township" },
  { rank: 120, name: "Windsor township" },
  { rank: 121, name: "Doylestown township" },
  { rank: 122, name: "Upper Saucon township" },
  { rank: 123, name: "Towamencin township" },
  { rank: 124, name: "Johnstown" },
  { rank: 125, name: "Hampton township" },
  { rank: 126, name: "Fairview township" },
  { rank: 127, name: "East Lampeter township" },
  { rank: 128, name: "West Lampeter township" },
  { rank: 129, name: "Upper Gwynedd township" },
  { rank: 130, name: "West Hempfield township" },
  { rank: 131, name: "Middletown township" },
  { rank: 132, name: "North Strabane township" },
{ rank: 133, name: "McKeesport" },
{ rank: 134, name: "South Middleton township" },
{ rank: 135, name: "Hilltown township" },
{ rank: 136, name: "Scott township" },
{ rank: 137, name: "Upper Chichester township" },
{ rank: 138, name: "Butler township" },
{ rank: 139, name: "Aston township" },
{ rank: 140, name: "Hanover" },
{ rank: 141, name: "Forks township" },
{ rank: 142, name: "Harborcreek township" },
{ rank: 143, name: "Chestnuthill township" },
{ rank: 144, name: "Lower Salford township" },
{ rank: 145, name: "Antrim township" },
{ rank: 146, name: "West Norriton township" },
{ rank: 147, name: "Newberry township" },
{ rank: 148, name: "North Fayette township" },
{ rank: 149, name: "Adams township" },
{ rank: 150, name: "Hermitage" },
{ rank: 151, name: "Middle Smithfield township" },
{ rank: 152, name: "North Whitehall township" },
{ rank: 153, name: "Cumru township" },
{ rank: 154, name: "Washington township" },
{ rank: 155, name: "Robinson township" },
{ rank: 156, name: "Patton township" },
{ rank: 157, name: "Pine township" },
{ rank: 158, name: "Caln township" },
{ rank: 159, name: "Newtown township" },
{ rank: 160, name: "White township" },
{ rank: 161, name: "Cecil township" },
{ rank: 162, name: "Upper Southampton township" },
{ rank: 163, name: "East Whiteland township" },
{ rank: 164, name: "Guilford township" },
{ rank: 165, name: "Franklin Park" },
{ rank: 166, name: "Warwick township" },
{ rank: 167, name: "West Bradford township" },
{ rank: 168, name: "Plumstead township" },
{ rank: 169, name: "Greensburg" },
{ rank: 170, name: "Skippack township" },
{ rank: 171, name: "Nether Providence township" },
{ rank: 172, name: "Whitehall" },
{ rank: 173, name: "Indiana" },
{ rank: 174, name: "Richland township" },
{ rank: 175, name: "Dunmore" },
{ rank: 176, name: "Lower Moreland township" },
{ rank: 177, name: "East Norriton township" },
{ rank: 178, name: "South Park township" },
{ rank: 179, name: "Spring Garden township" },
{ rank: 180, name: "Wilkinsburg" },
{ rank: 181, name: "Ephrata" },
{ rank: 182, name: "Salisbury township" },
{ rank: 183, name: "Washington" },
{ rank: 184, name: "New Hanover township" },
{ rank: 185, name: "Franconia township" },
{ rank: 186, name: "Upper Uwchlan township" },
{ rank: 187, name: "Amity township" },
{ rank: 188, name: "Derry township" },
{ rank: 189, name: "Pottsville" },
{ rank: 190, name: "Kingston" },
{ rank: 191, name: "Hopewell township" },
{ rank: 192, name: "Coatesville" },
{ rank: 193, name: "Bloomsburg" },
{ rank: 194, name: "Dingman township" },
{ rank: 195, name: "Lower Pottsgrove township" },
{ rank: 196, name: "Butler" },
{ rank: 197, name: "North Middleton township" },
{ rank: 198, name: "Sharon" },
{ rank: 199, name: "Elizabeth township" },
{ rank: 200, name: "Yeadon" },
{ rank: 201, name: "St. Marys" },
{ rank: 202, name: "Rapho township" },
{ rank: 203, name: "New Britain township" },
{ rank: 204, name: "Lower Gwynedd township" },
{ rank: 205, name: "North Lebanon township" },
{ rank: 206, name: "Meadville" },
{ rank: 207, name: "Emmaus" },
{ rank: 208, name: "Logan township" },
{ rank: 209, name: "Elizabethtown" },
{ rank: 210, name: "Jefferson Hills" },
{ rank: 211, name: "West Deer township" },
{ rank: 212, name: "Richland township" },
{ rank: 213, name: "New Kensington" },
{ rank: 214, name: "Center township" },
{ rank: 215, name: "Richland township" },
{ rank: 216, name: "Hanover township" },
{ rank: 217, name: "Hamilton township" },
{ rank: 218, name: "Salisbury township" },
{ rank: 219, name: "Hanover township" },
{ rank: 220, name: "Sandy township" },
{ rank: 221, name: "Lower Burrell" },
{ rank: 222, name: "Worcester township" },
{ rank: 223, name: "Rostraver township" },
{ rank: 224, name: "New Garden township" },
{ rank: 225, name: "Somerset township" },
{ rank: 226, name: "Loyalsock township" },
{ rank: 227, name: "Fairview township" },
{ rank: 228, name: "Willistown township" },
{ rank: 229, name: "North Union township" },
{ rank: 230, name: "Westtown township" },
{ rank: 231, name: "West Manheim township" },
{ rank: 232, name: "West Hanover township" },
{ rank: 233, name: "Lehman township" },
{ rank: 234, name: "Wyomissing" },
{ rank: 235, name: "Waynesboro" },
{ rank: 236, name: "Lansdowne" },
{ rank: 237, name: "East Bradford township" },
{ rank: 238, name: "Easttown township" },
{ rank: 239, name: "Lower Saucon township" },
{ rank: 240, name: "Penn township" },
{ rank: 241, name: "East Cocalico township" },
{ rank: 242, name: "Douglass township" },
{ rank: 243, name: "College township" },
{ rank: 244, name: "Mount Joy township" },
{ rank: 245, name: "Upper Providence township" },
{ rank: 246, name: "Lehigh township" },
{ rank: 247, name: "Ephrata township" },
{ rank: 248, name: "Pocono township" },
{ rank: 249, name: "Nanticoke" },
{ rank: 250, name: "South Lebanon township" },
{ rank: 251, name: "Darby" },
{ rank: 252, name: "Columbia" },
{ rank: 253, name: "Northampton" },
{ rank: 254, name: "South Union township" },
{ rank: 255, name: "Penn Forest township" },
{ rank: 256, name: "East Brandywine township" },
{ rank: 257, name: "Hazle township" },
{ rank: 258, name: "Munhall" },
{ rank: 259, name: "Berwick" },
{ rank: 260, name: "Milford township" },
{ rank: 261, name: "Marshall township" },
{ rank: 262, name: "Mechanicsburg" },
{ rank: 263, name: "Butler township" },
{ rank: 264, name: "Coal township" },
{ rank: 265, name: "Mount Pleasant township" },
{ rank: 266, name: "Plains township" },
{ rank: 267, name: "Bristol" },
{ rank: 268, name: "Lititz" },
{ rank: 269, name: "Lower Swatara township" },
{ rank: 270, name: "North Cornwall township" },
{ rank: 271, name: "Millersville" },
{ rank: 272, name: "Harrison township" },
{ rank: 273, name: "Morrisville" },
{ rank: 274, name: "Bethel township" },
{ rank: 275, name: "South Abington township" },
{ rank: 276, name: "Middletown" },
{ rank: 277, name: "Neshannock township" },
{ rank: 278, name: "North Versailles township" },
{ rank: 279, name: "Canonsburg" },
{ rank: 280, name: "Brentwood" },
{ rank: 281, name: "South Strabane township" },
{ rank: 282, name: "Sunbury" },
{ rank: 283, name: "Uniontown" },
{ rank: 284, name: "Moore township" },
{ rank: 285, name: "Benner township" },
{ rank: 286, name: "Perkasie" },
{ rank: 287, name: "Oil City" },
{ rank: 288, name: "North Codorus township" },
{ rank: 289, name: "Jackson township" },
{ rank: 290, name: "Conshohocken" },
{ rank: 291, name: "Dallas township" },
{ rank: 292, name: "Quakertown" },
{ rank: 293, name: "Maidencreek township" },
{ rank: 294, name: "Chartiers township" },
{ rank: 295, name: "West Donegal township" },
{ rank: 296, name: "Kennett township" },
{ rank: 297, name: "Darby township" },
{ rank: 298, name: "Jackson township" },
{ rank: 299, name: "East Nottingham township" },
{ rank: 300, name: "Warren" },
{ rank: 301, name: "London Grove township" },
{ rank: 302, name: "North Londonderry township" },
{ rank: 303, name: "Aliquippa" },
{ rank: 304, name: "West Caln township" },
{ rank: 305, name: "Upper Leacock township" },
{ rank: 306, name: "Perkiomen township" },
{ rank: 307, name: "Conewago township" },
{ rank: 308, name: "Collier township" },
{ rank: 309, name: "Economy" },
{ rank: 310, name: "Gettysburg" },
{ rank: 311, name: "O'Hara township" },
{ rank: 312, name: "Schuylkill township" },
{ rank: 313, name: "East Stroudsburg" },
{ rank: 314, name: "Upper Makefield township" },
{ rank: 315, name: "Collingdale" },
{ rank: 316, name: "Carbondale" },
{ rank: 317, name: "South Londonderry township" },
{ rank: 318, name: "Brighton township" },
{ rank: 319, name: "East Donegal township" },
{ rank: 320, name: "East Pikeland township" },
{ rank: 321, name: "Beaver Falls" },
{ rank: 322, name: "Bushkill township" },
{ rank: 323, name: "East Manchester township" },
{ rank: 324, name: "Upper Hanover township" },
{ rank: 325, name: "Old Forge" },
{ rank: 326, name: "Solebury township" },
{ rank: 327, name: "Southampton township" },
{ rank: 328, name: "Lock Haven" },
{ rank: 329, name: "Jeannette" },
{ rank: 330, name: "Upper Nazareth township" },
{ rank: 331, name: "Southampton township" },
{ rank: 332, name: "West Earl township" },
{ rank: 333, name: "Hamilton township" },
{ rank: 334, name: "Downingtown" },
{ rank: 335, name: "Slippery Rock township" },
{ rank: 336, name: "Honey Brook township" },
{ rank: 337, name: "Lewistown" },
{ rank: 338, name: "North Coventry township" },
{ rank: 339, name: "Maxatawny township" },
{ rank: 340, name: "Doylestown" },
{ rank: 341, name: "Mount Joy" },
{ rank: 342, name: "Kennedy township" },
{ rank: 343, name: "Brookhaven" },
{ rank: 344, name: "Pleasant Hills" },
{ rank: 345, name: "Hatboro" },
{ rank: 346, name: "Canton township" },
{ rank: 347, name: "Tobyhanna township" },
{ rank: 348, name: "Buffalo township" },
{ rank: 349, name: "Upper Milford township" },
{ rank: 350, name: "Swissvale" },
{ rank: 351, name: "Camp Hill" },
{ rank: 352, name: "Allegheny township" },
{ rank: 353, name: "Chippewa township" },
{ rank: 354, name: "Wilson" },
{ rank: 355, name: "Spring township" },
{ rank: 356, name: "Conewago township" },
{ rank: 357, name: "Castle Shannon" },
{ rank: 358, name: "East Marlborough township" },
{ rank: 359, name: "Valley township" },
{ rank: 360, name: "West Brandywine township" },
{ rank: 361, name: "Bellevue" },
{ rank: 362, name: "Latrobe" },
{ rank: 363, name: "East Fallowfield township" },
{ rank: 364, name: "Dormont" },
{ rank: 365, name: "East Vincent township" },
{ rank: 366, name: "Center township" },
{ rank: 367, name: "Smithfield township" },
{ rank: 368, name: "South Heidelberg township" },
{ rank: 369, name: "Carnegie" },
{ rank: 370, name: "Grove City" },
{ rank: 371, name: "Robeson township" },
{ rank: 372, name: "Brecknock township" },
{ rank: 373, name: "Delaware township" },
{ rank: 374, name: "Palmyra" },
{ rank: 375, name: "Pittston" },
{ rank: 376, name: "Frankstown township" },
{ rank: 377, name: "Lower Windsor township" },
{ rank: 378, name: "West Cocalico township" },
{ rank: 379, name: "New Cumberland" },
{ rank: 380, name: "East Huntingdon township" },
{ rank: 381, name: "Archbald" },
{ rank: 382, name: "Bedminster township" },
{ rank: 383, name: "Bradford" },
{ rank: 384, name: "Middlesex township" },
{ rank: 385, name: "East Buffalo township" },
{ rank: 386, name: "Ellwood City" },
{ rank: 387, name: "Polk township" },
{ rank: 388, name: "Ohio township" },
{ rank: 389, name: "Souderton" },
{ rank: 390, name: "Lawrence township" },
{ rank: 391, name: "South Hanover township" },
{ rank: 392, name: "DuBois" },
{ rank: 393, name: "Carroll township" },
{ rank: 394, name: "White Oak" },
{ rank: 395, name: "Summit township" },
{ rank: 396, name: "Providence township" },
{ rank: 397, name: "Shrewsbury township" },
{ rank: 398, name: "Indiana township" },
{ rank: 399, name: "Derry township" },
{ rank: 400, name: "Middlesex township" },
{ rank: 401, name: "Ridley Park" },
{ rank: 402, name: "Cumberland township" },
{ rank: 403, name: "Earl township" },
{ rank: 404, name: "Glenolden" },
{ rank: 405, name: "East Coventry township" },
{ rank: 406, name: "Kingston township" },
{ rank: 407, name: "Lower Nazareth township" },
{ rank: 408, name: "New Sewickley township" },
{ rank: 409, name: "Clay township" },
{ rank: 410, name: "Shenango township" },
{ rank: 411, name: "Huntingdon" },
{ rank: 412, name: "Tamaqua" },
{ rank: 413, name: "Thornbury township" },
{ rank: 414, name: "Ambler" },
{ rank: 415, name: "Tunkhannock township" },
{ rank: 416, name: "West Vincent township" },
{ rank: 417, name: "Ambridge" },
{ rank: 418, name: "East Earl township" },
{ rank: 419, name: "Franklin township" },
{ rank: 420, name: "Lower Heidelberg township" },
{ rank: 421, name: "Clifton Heights" },
{ rank: 422, name: "Washington township" },
{ rank: 423, name: "Shamokin" },
{ rank: 424, name: "Bern township" },
{ rank: 425, name: "Monroe township" },
{ rank: 426, name: "Folcroft" },
{ rank: 427, name: "Kennett Square" },
{ rank: 428, name: "Pequea township" },
{ rank: 429, name: "Monessen" },
{ rank: 430, name: "Blakely" },
{ rank: 431, name: "Williams township" },
{ rank: 432, name: "Connellsville" },
{ rank: 433, name: "Oakmont" },
{ rank: 434, name: "Conemaugh township" },
{ rank: 435, name: "Washington township" },
{ rank: 436, name: "Findlay township" },
{ rank: 437, name: "Swarthmore" },
{ rank: 438, name: "Allegheny township" },
{ rank: 439, name: "Red Lion" },
{ rank: 440, name: "Milton" },
{ rank: 441, name: "Catasauqua" },
{ rank: 442, name: "Upper Pottsgrove township" },
{ rank: 443, name: "North East township" },
{ rank: 444, name: "Bullskin township" },
{ rank: 445, name: "Upper Mount Bethel township" },
{ rank: 446, name: "Jackson township" },
{ rank: 447, name: "Charlestown township" },
{ rank: 448, name: "Prospect Park" },
{ rank: 449, name: "West View" },
{ rank: 450, name: "Dunbar township" },
{ rank: 451, name: "Steelton" },
{ rank: 452, name: "Antis township" },
{ rank: 453, name: "Taylor" },
{ rank: 454, name: "Plainfield township" },
{ rank: 455, name: "Cranberry township" },
{ rank: 456, name: "South Williamsport" },
{ rank: 457, name: "Stowe township" },
{ rank: 458, name: "Hellertown" },
{ rank: 459, name: "Forest Hills" },
{ rank: 460, name: "Edinboro" },
{ rank: 461, name: "Springfield township" },
{ rank: 462, name: "Cumberland township" },
{ rank: 463, name: "Oxford township" },
{ rank: 464, name: "Nazareth" },
{ rank: 465, name: "Wilkins township" },
{ rank: 466, name: "Georges township" },
{ rank: 467, name: "Corry" },
{ rank: 468, name: "St. Thomas township" },
{ rank: 469, name: "Dickson City" },
{ rank: 470, name: "Moosic" },
{ rank: 471, name: "Chanceford township" },
{ rank: 472, name: "Salem township" },
{ rank: 473, name: "East Hanover township" },
{ rank: 474, name: "Ligonier township" },
{ rank: 475, name: "Reading township" },
{ rank: 476, name: "Sharon Hill" },
{ rank: 477, name: "Hellam township" },
{ rank: 478, name: "Jackson township" },
{ rank: 479, name: "Franklin" },
{ rank: 480, name: "Bellefonte" },
{ rank: 481, name: "Oxford" },
{ rank: 482, name: "Clairton" },
{ rank: 483, name: "Norwood" },
{ rank: 484, name: "Harris township" },
{ rank: 485, name: "Media" },
{ rank: 486, name: "Somerset" },
{ rank: 487, name: "New London township" },
{ rank: 488, name: "Lower Oxford township" },
{ rank: 489, name: "Montgomery township" },
{ rank: 490, name: "Stroudsburg" },
{ rank: 491, name: "Crafton" },
{ rank: 492, name: "East Rockhill township" },
{ rank: 493, name: "Clearfield" },
{ rank: 494, name: "Plymouth" },
{ rank: 495, name: "Wright township" },
{ rank: 496, name: "New Holland" },
{ rank: 497, name: "East Caln township" },
{ rank: 498, name: "Leacock township" },
{ rank: 499, name: "Paradise township" },
{ rank: 500, name: "Penn township" },
{ rank: 501, name: "Cambria township" },
{ rank: 502, name: "Longswamp township" },
{ rank: 503, name: "Blooming Grove township" },
{ rank: 504, name: "West Pennsboro township" },
{ rank: 505, name: "Shippensburg" },
{ rank: 506, name: "McKees Rocks" },
{ rank: 507, name: "Palmerton" },
{ rank: 508, name: "Adams township" },
{ rank: 509, name: "Scott township" },
{ rank: 510, name: "Mount Carmel" },
{ rank: 511, name: "Punxsutawney" },
{ rank: 512, name: "Sewickley township" },
{ rank: 513, name: "Exeter" },
{ rank: 514, name: "Selinsgrove" },
{ rank: 515, name: "New Brighton" },
{ rank: 516, name: "Hopewell township" },
{ rank: 517, name: "West Rockhill township" },
{ rank: 518, name: "Union township" },
{ rank: 519, name: "Greenville" },
{ rank: 520, name: "Hollidaysburg" },
{ rank: 521, name: "Shillington" },
{ rank: 522, name: "Collegeville" },
{ rank: 523, name: "Allen township" },
{ rank: 524, name: "Monaca" },
{ rank: 525, name: "Ross township" },
{ rank: 526, name: "North Sewickley township" },
{ rank: 527, name: "Dickinson township" },
{ rank: 528, name: "Bridgeport" },
{ rank: 529, name: "East Allen township" },
{ rank: 530, name: "Olyphant" },
{ rank: 531, name: "Sayre" },
{ rank: 532, name: "Bethel township" },
{ rank: 533, name: "Lackawaxen township" },
{ rank: 534, name: "Wayne township" },
{ rank: 535, name: "South Huntingdon township" },
{ rank: 536, name: "Quincy township" },
{ rank: 537, name: "Carroll township" },
{ rank: 538, name: "Lewisburg" },
{ rank: 539, name: "Tyrone" },
{ rank: 540, name: "Coraopolis" },
{ rank: 541, name: "Carroll township" },
{ rank: 542, name: "Schuylkill Haven" },
{ rank: 543, name: "Lehighton" },
{ rank: 544, name: "Vernon township" },
{ rank: 545, name: "Springfield township" },
{ rank: 546, name: "Franklin township" },
{ rank: 547, name: "West Hazleton" },
{ rank: 548, name: "Martic township" },
{ rank: 549, name: "Washington township" },
{ rank: 550, name: "New Freedom" },
{ rank: 551, name: "Titusville" },
{ rank: 552, name: "Fox Chapel" },
{ rank: 553, name: "Colebrookdale township" },
{ rank: 554, name: "Luzerne township" },
{ rank: 555, name: "Bangor" },
{ rank: 556, name: "Athens township" },
{ rank: 557, name: "Birdsboro" },
{ rank: 558, name: "Duryea" },
{ rank: 559, name: "West York" },
{ rank: 560, name: "Middle Paxton township" },
{ rank: 561, name: "Clarks Summit" },
{ rank: 562, name: "Peach Bottom township" },
{ rank: 563, name: "Jefferson township" },
{ rank: 564, name: "Butler township" },
{ rank: 565, name: "Bedford township" },
{ rank: 566, name: "Swoyersville" },
{ rank: 567, name: "Weisenberg township" },
{ rank: 568, name: "Upper Yoder township" },
{ rank: 569, name: "Duquesne" },
{ rank: 570, name: "Swatara township" }
]

interface PennsylvaniaCitySelectorProps {
  onCitySelect: (city: City) => void
  selectedCities: string[]
}

const PennsylvaniaCitySelector: React.FC<PennsylvaniaCitySelectorProps> = ({ onCitySelect, selectedCities }) => {
  return (
    <div className="space-y-2">
      <label htmlFor="city-select" className="block text-sm font-medium text-[#E4B649]">
        Select a Pennsylvania City
      </label>
      <Select onValueChange={(value) => {
        const selectedCity = PENNSYLVANIA_CITIES.find(city => city.name === value)
        if (selectedCity) onCitySelect(selectedCity)
      }}>
        <SelectTrigger id="city-select" className="w-full bg-black/50 border-[#E4B649]/20 text-white">
          <SelectValue placeholder="Choose a city" />
        </SelectTrigger>
        <SelectContent className="bg-black border-[#E4B649]/20">
          <ScrollArea className="h-[200px]">
            {PENNSYLVANIA_CITIES.map((city) => (
              <SelectItem 
                key={city.rank} 
                value={city.name}
                className="text-white hover:bg-[#E4B649]/20"
                disabled={selectedCities.includes(city.name)}
              >
                {city.name}
              </SelectItem>
            ))}
          </ScrollArea>
        </SelectContent>
      </Select>
      <p className="text-xs text-[#E4B649]/70">
        * You can select up to 10 cities from Pennsylvania
      </p>
    </div>
  )
}

export default PennsylvaniaCitySelector
