import React from 'react'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { ScrollArea } from "@/components/ui/scroll-area"

interface City {
  name: string
  rank: number
}

const TEXAS_CITIES: City[] = [
  { rank: 1, name: "Houston" },
  { rank: 2, name: "San Antonio" },
  { rank: 3, name: "Dallas" },
  { rank: 4, name: "Fort Worth" },
  { rank: 5, name: "Austin" },
  { rank: 6, name: "El Paso" },
  { rank: 7, name: "Arlington" },
  { rank: 8, name: "Corpus Christi" },
  { rank: 9, name: "Plano" },
  { rank: 10, name: "Lubbock" },
  { rank: 11, name: "Laredo" },
  { rank: 12, name: "Irving" },
  { rank: 13, name: "Garland" },
  { rank: 14, name: "Frisco" },
  { rank: 15, name: "McKinney" },
  { rank: 16, name: "Grand Prairie" },
  { rank: 17, name: "Amarillo" },
  { rank: 18, name: "Brownsville" },
  { rank: 19, name: "Denton" },
  { rank: 20, name: "Killeen" },
  { rank: 21, name: "McAllen" },
  { rank: 22, name: "Mesquite" },
  { rank: 23, name: "Waco" },
  { rank: 24, name: "Pasadena" },
  { rank: 25, name: "Midland" },
  { rank: 26, name: "Lewisville" },
  { rank: 27, name: "Round Rock" },
  { rank: 28, name: "Carrollton" },
  { rank: 29, name: "Abilene" },
  { rank: 30, name: "Pearland" },
  { rank: 31, name: "College Station" },
  { rank: 32, name: "The Woodlands" },
  { rank: 33, name: "New Braunfels" },
  { rank: 34, name: "League City" },
  { rank: 35, name: "Richardson" },
  { rank: 36, name: "Odessa" },
  { rank: 37, name: "Conroe" },
  { rank: 38, name: "Allen" },
  { rank: 39, name: "Tyler" },
  { rank: 40, name: "Beaumont" },
  { rank: 41, name: "Sugar Land" },
  { rank: 42, name: "Edinburg" },
  { rank: 43, name: "Georgetown" },
  { rank: 44, name: "Wichita Falls" },
  { rank: 45, name: "San Angelo" },
  { rank: 46, name: "Temple" },
  { rank: 47, name: "Atascocita" },
  { rank: 48, name: "Bryan" },
  { rank: 49, name: "Mission" },
  { rank: 50, name: "Leander" },
  { rank: 51, name: "Longview" },
  { rank: 52, name: "Baytown" },
  { rank: 53, name: "Pharr" },
  { rank: 54, name: "Mansfield" },
  { rank: 55, name: "Flower Mound" },
  { rank: 56, name: "Missouri City" },
  { rank: 57, name: "Cedar Park" },
  { rank: 58, name: "San Marcos" },
  { rank: 59, name: "Harlingen" },
  { rank: 60, name: "North Richland Hills" },
  { rank: 61, name: "Rowlett" },
  { rank: 62, name: "Kyle" },
  { rank: 63, name: "Victoria" },
  { rank: 64, name: "Spring" },
  { rank: 65, name: "Pflugerville" },
  { rank: 66, name: "Little Elm" },
  { rank: 67, name: "Wylie" },
  { rank: 68, name: "Euless" },
  { rank: 69, name: "Texas City" },
  { rank: 70, name: "Burleson" },
  { rank: 71, name: "DeSoto" },
  { rank: 72, name: "Port Arthur" },
  { rank: 73, name: "Rockwall" },
  { rank: 74, name: "Galveston" },
  { rank: 75, name: "Celina" },
  { rank: 76, name: "Grapevine" },
  { rank: 77, name: "Fulshear" },
  { rank: 78, name: "Huntsville" },
  { rank: 79, name: "Waxahachie" },
  { rank: 80, name: "Sherman" },
  { rank: 81, name: "Cedar Hill" },
  { rank: 82, name: "Bedford" },
  { rank: 83, name: "Keller" },
  { rank: 84, name: "The Colony" },
  { rank: 85, name: "Prosper" },
  { rank: 86, name: "Haltom City" },
  { rank: 87, name: "Channelview" },
  { rank: 88, name: "Weslaco" },
  { rank: 89, name: "Schertz" },
  { rank: 90, name: "Midlothian" },
  { rank: 91, name: "Hutto" },
  { rank: 92, name: "Rosenberg" },
  { rank: 93, name: "Coppell" },
  { rank: 94, name: "Friendswood" },
  { rank: 95, name: "Weatherford" },
  { rank: 96, name: "Lancaster" },
  { rank: 97, name: "Socorro" },
  { rank: 98, name: "Copperas Cove" },
  { rank: 99, name: "Forney" },
  { rank: 100, name: "Hurst" },
  { rank: 101, name: "Duncanville" },
  { rank: 102, name: "Seguin" },
  { rank: 103, name: "Mission Bend" },
  { rank: 104, name: "Cleburne" },
  { rank: 105, name: "Timberwood Park" },
  { rank: 106, name: "Cibolo" },
  { rank: 107, name: "La Porte" },
  { rank: 108, name: "Farmers Branch" },
  { rank: 109, name: "San Juan" },
  { rank: 110, name: "Texarkana" },
  { rank: 111, name: "Harker Heights" },
  { rank: 112, name: "Del Rio" },
  { rank: 113, name: "Lufkin" },
  { rank: 114, name: "Greenville" },
  { rank: 115, name: "Sachse" },
  { rank: 116, name: "Canyon Lake" },
  { rank: 117, name: "Deer Park" },
  { rank: 118, name: "West Odessa" },
  { rank: 119, name: "Nacogdoches" },
  { rank: 120, name: "Princeton" },
  { rank: 121, name: "Converse" },
  { rank: 122, name: "Southlake" },
  { rank: 123, name: "Anna" },
  { rank: 124, name: "Alvin" },
  { rank: 125, name: "Eagle Pass" },
  { rank: 126, name: "Katy" },
  { rank: 127, name: "Lake Jackson" },
  { rank: 128, name: "Royse City" },
  { rank: 129, name: "Sienna" },
  { rank: 130, name: "Denison" },
  { rank: 131, name: "Fate" },
  { rank: 132, name: "Melissa" },
  { rank: 133, name: "Balch Springs" },
  { rank: 134, name: "Belton" },
  { rank: 135, name: "Corsicana" },
  { rank: 136, name: "Colleyville" },
  { rank: 137, name: "Saginaw" },
  { rank: 138, name: "Kerrville" },
  { rank: 139, name: "Paris" },
  { rank: 140, name: "Cloverleaf" },
  { rank: 141, name: "University Park" },
  { rank: 142, name: "Ennis" },
  { rank: 143, name: "Fort Hood" },
  { rank: 144, name: "Horizon City" },
  { rank: 145, name: "San Benito" },
  { rank: 146, name: "Marshall" },
  { rank: 147, name: "Fresno" },
  { rank: 148, name: "Kingsville" },
  { rank: 149, name: "Benbrook" },
  { rank: 150, name: "Corinth" },
  { rank: 151, name: "Pecan Grove" },
  { rank: 152, name: "Boerne" },
  { rank: 153, name: "Terrell" },
  { rank: 154, name: "Watauga" },
  { rank: 155, name: "Brushy Creek" },
  { rank: 156, name: "Manor" },
  { rank: 157, name: "Stephenville" },
  { rank: 158, name: "Alton" },
  { rank: 159, name: "Dickinson" },
  { rank: 160, name: "Big Spring" },
  { rank: 161, name: "Murphy" },
  { rank: 162, name: "Steiner Ranch" },
  { rank: 163, name: "Alamo" },
  { rank: 164, name: "Portland" },
  { rank: 165, name: "Angleton" },
  { rank: 166, name: "Crowley" },
  { rank: 167, name: "Universal City" },
  { rank: 168, name: "Red Oak" },
  { rank: 169, name: "Seagoville" },
  { rank: 170, name: "La Marque" },
  { rank: 171, name: "Brenham" },
  { rank: 172, name: "Glenn Heights" },
  { rank: 173, name: "Palestine" },
  { rank: 174, name: "Manvel" },
  { rank: 175, name: "Plainview" },
  { rank: 176, name: "Lakeway" },
  { rank: 177, name: "Orange" },
  { rank: 178, name: "Cinco Ranch" },
  { rank: 179, name: "Brownwood" },
  { rank: 180, name: "Gainesville" },
  { rank: 181, name: "White Settlement" },
  { rank: 182, name: "Nederland" },
  { rank: 183, name: "Taylor" },
  { rank: 184, name: "Alice" },
  { rank: 185, name: "Bay City" },
  { rank: 186, name: "Stafford" },
  { rank: 187, name: "Addison" },
  { rank: 188, name: "Bellaire" },
  { rank: 189, name: "Iowa Colony" },
  { rank: 190, name: "Hewitt" },
  { rank: 191, name: "Mercedes" },
  { rank: 192, name: "Donna" },
  { rank: 193, name: "Sulphur Springs" },
  { rank: 194, name: "Canyon" },
  { rank: 195, name: "Groves" },
  { rank: 196, name: "Pampa" },
  { rank: 197, name: "Buda" },
  { rank: 198, name: "Gatesville" },
  { rank: 199, name: "Highland Village" },
  { rank: 200, name: "Humble" },
  { rank: 201, name: "Live Oak" },
  { rank: 202, name: "Mount Pleasant" },
  { rank: 203, name: "Rendon" },
  { rank: 204, name: "Palmview" },
  { rank: 205, name: "South Houston" },
  { rank: 206, name: "Mineral Wells" },
  { rank: 207, name: "Lockhart" },
  { rank: 208, name: "Uvalde" },
  { rank: 209, name: "Aldine" },
  { rank: 210, name: "Rio Grande City" },
  { rank: 211, name: "Azle" },
  { rank: 212, name: "Hidalgo" },
  { rank: 213, name: "Tomball" },
  { rank: 214, name: "West University Place" },
  { rank: 215, name: "Hereford" },
  { rank: 216, name: "Jacksonville" },
  { rank: 217, name: "Lumberton" },
  { rank: 218, name: "Dumas" },
  { rank: 219, name: "Wells Branch" },
  { rank: 220, name: "Forest Hill" },
  { rank: 221, name: "Athens" },
  { rank: 222, name: "Seabrook" },
  { rank: 223, name: "Trophy Club" },
  { rank: 224, name: "Kilgore" },
  { rank: 225, name: "Port Neches" },
  { rank: 226, name: "Henderson" },
  { rank: 227, name: "Andrews" },
  { rank: 228, name: "Richmond" },
  { rank: 229, name: "Fort Bliss" },
  { rank: 230, name: "Robinson" },
  { rank: 231, name: "Granbury" },
  { rank: 232, name: "Elgin" },
  { rank: 233, name: "Beeville" },
  { rank: 234, name: "Santa Fe" },
  { rank: 235, name: "Liberty Hill" },
  { rank: 236, name: "Lantana" },
  { rank: 237, name: "Levelland" },
  { rank: 238, name: "Bastrop" },
  { rank: 239, name: "Webster" },
  { rank: 240, name: "Borger" },
  { rank: 241, name: "El Campo" },
  { rank: 242, name: "Fair Oaks Ranch" },
  { rank: 243, name: "Selma" },
  { rank: 244, name: "Hornsby Bend" },
  { rank: 245, name: "Heath" },
  { rank: 246, name: "Fredericksburg" },
  { rank: 247, name: "Roma" },
  { rank: 248, name: "Pleasanton" },
  { rank: 249, name: "Four Corners" },
  { rank: 250, name: "Leon Valley" },
  { rank: 251, name: "Rockport" },
  { rank: 252, name: "Roanoke" },
  { rank: 253, name: "Burkburnett" },
  { rank: 254, name: "Port Lavaca" },
  { rank: 255, name: "Snyder" },
  { rank: 256, name: "Bonham" },
  { rank: 257, name: "Fairview" },
  { rank: 258, name: "Scenic Oaks" },
  { rank: 259, name: "Northlake" },
  { rank: 260, name: "Clute" },
  { rank: 261, name: "Bellmead" },
  { rank: 262, name: "Bacliff" },
  { rank: 263, name: "Kennedale" },
  { rank: 264, name: "Freeport" },
  { rank: 265, name: "La Homa" },
  { rank: 266, name: "Robstown" },
  { rank: 267, name: "Lago Vista" },
  { rank: 268, name: "Ingleside" },
  { rank: 269, name: "Helotes" },
  { rank: 270, name: "Mont Belvieu" },
  { rank: 271, name: "San Elizario" },
  { rank: 272, name: "Sweetwater" },
  { rank: 273, name: "Galena Park" },
  { rank: 274, name: "Sanger" },
  { rank: 275, name: "Travis Ranch" },
  { rank: 276, name: "Heartland" },
  { rank: 277, name: "Raymondville" },
  { rank: 278, name: "Whitehouse" },
  { rank: 279, name: "Dayton" },
  { rank: 280, name: "Dripping Springs" },
  { rank: 281, name: "Eidson Road" },
  { rank: 282, name: "Kaufman" },
  { rank: 283, name: "Woodway" },
  { rank: 284, name: "Vidor" },
  { rank: 285, name: "Bridge City" },
  { rank: 286, name: "Vernon" },
  { rank: 287, name: "Cleveland" },
  { rank: 288, name: "Providence Village" },
  { rank: 289, name: "Commerce" },
  { rank: 290, name: "Paloma Creek South" },
  { rank: 291, name: "Sonterra" },
  { rank: 292, name: "Navasota" },
  { rank: 293, name: "Aubrey" },
  { rank: 294, name: "Joshua" },
  { rank: 295, name: "Jacinto City" },
  { rank: 296, name: "Aransas Pass" },
  { rank: 297, name: "Pearsall" },
  { rank: 298, name: "Murillo" },
  { rank: 299, name: "Pecos" },
  { rank: 300, name: "Lucas" },
  { rank: 301, name: "Hondo" },
  { rank: 302, name: "Liberty" },
  { rank: 303, name: "Hillsboro" },
  { rank: 304, name: "Graham" },
  { rank: 305, name: "Wharton" },
  { rank: 306, name: "Josephine" },
  { rank: 307, name: "Sunnyvale" },
  { rank: 308, name: "Floresville" },
  { rank: 309, name: "Prairie View" },
  { rank: 310, name: "Highland Park" },
  { rank: 311, name: "Brownfield" },
  { rank: 312, name: "Venus" },
  { rank: 313, name: "Lavon" },
  { rank: 314, name: "Decatur" },
  { rank: 315, name: "Bee Cave" },
  { rank: 316, name: "Los Fresnos" },
  { rank: 317, name: "Dalhart" },
  { rank: 318, name: "Richland Hills" },
  { rank: 319, name: "Cuero" },
  { rank: 320, name: "Perryton" },
  { rank: 321, name: "Lamesa" },
  { rank: 322, name: "Lampasas" },
  { rank: 323, name: "Kirby" },
  { rank: 324, name: "Fort Stockton" },
  { rank: 325, name: "Lake Dallas" },
  { rank: 326, name: "Homestead Meadows South" },
  { rank: 327, name: "Hitchcock" },
  { rank: 328, name: "Wolfforth" },
  { rank: 329, name: "Belterra" },
  { rank: 330, name: "Mila Doce" },
  { rank: 331, name: "Marble Falls" },
  { rank: 332, name: "Jasper" },
  { rank: 333, name: "Jersey Village" },
  { rank: 334, name: "Van Alstyne" },
  { rank: 335, name: "Alamo Heights" },
  { rank: 336, name: "West Livingston" },
  { rank: 337, name: "Sealy" },
  { rank: 338, name: "Bulverde" },
  { rank: 339, name: "Olivarez" },
  { rank: 340, name: "Nolanville" },
  { rank: 341, name: "Lacy-Lakeview" },
  { rank: 342, name: "Highlands" },
  { rank: 343, name: "Seminole" },
  { rank: 344, name: "Savannah" },
  { rank: 345, name: "River Oaks" },
  { rank: 346, name: "Kingsland" },
  { rank: 347, name: "Gonzales" },
  { rank: 348, name: "Salida Sol Estates" },
  { rank: 349, name: "Lindale" },
  { rank: 350, name: "Willow Park" },
  { rank: 351, name: "Mabank" },
  { rank: 352, name: "Willis" },
  { rank: 353, name: "Monahans" },
  { rank: 354, name: "Burnet" },
  { rank: 355, name: "Gun Barrel City" },
  { rank: 356, name: "Keene" },
  { rank: 357, name: "Camp Swift" },
  { rank: 358, name: "Homestead Meadows North" },
  { rank: 359, name: "Oak Point" },
  { rank: 360, name: "Pecan Plantation" },
  { rank: 361, name: "Canutillo" },
  { rank: 362, name: "Hempstead" },
  { rank: 363, name: "Krum" },
  { rank: 364, name: "Mexia" },
  { rank: 365, name: "Aledo" },
  { rank: 366, name: "La Feria" },
  { rank: 367, name: "Silsbee" },
  { rank: 368, name: "Bridgeport" },
  { rank: 369, name: "Alvarado" },
  { rank: 370, name: "Wilmer" },
  { rank: 371, name: "Carthage" },
  { rank: 372, name: "Lackland AFB" },
  { rank: 373, name: "Iowa Park" },
  { rank: 374, name: "Doolittle" },
  { rank: 375, name: "Parker" },
  { rank: 376, name: "Pilot Point" },
  { rank: 377, name: "Justin" },
  { rank: 378, name: "Hutchins" },
  { rank: 379, name: "Argyle" },
  { rank: 380, name: "Briar" },
  { rank: 381, name: "Gladewater" },
  { rank: 382, name: "Penitas" },
  { rank: 383, name: "Magnolia" },
  { rank: 384, name: "Crockett" },
  { rank: 385, name: "White Oak" },
  { rank: 386, name: "McGregor" },
  { rank: 387, name: "Bowie" },
  { rank: 388, name: "Lakehills" },
  { rank: 389, name: "Alpine" },
  { rank: 390, name: "Crystal City" },
  { rank: 391, name: "Edna" },
  { rank: 392, name: "Hickory Creek" },
  { rank: 393, name: "Everman" },
  { rank: 394, name: "Kermit" },
  { rank: 395, name: "Brookshire" },
  { rank: 396, name: "Yoakum" },
  { rank: 397, name: "San Leon" },
  { rank: 398, name: "Luling" },
  { rank: 399, name: "Childress" },
  { rank: 400, name: "Wake Village" },
  { rank: 401, name: "Livingston" },
  { rank: 402, name: "Windcrest" },
  { rank: 403, name: "Littlefield" },
  { rank: 404, name: "Elsa" },
  { rank: 405, name: "Rockdale" },
  { rank: 406, name: "Cameron Park" },
  { rank: 407, name: "Slaton" },
  { rank: 408, name: "Sandy Oaks" },
  { rank: 409, name: "Marlin" },
  { rank: 410, name: "Cameron" },
  { rank: 411, name: "Sinton" },
  { rank: 412, name: "Granite Shoals" },
  { rank: 413, name: "North Alamo" },
  { rank: 414, name: "Atlanta" },
  { rank: 415, name: "Primera" },
  { rank: 416, name: "McLendon-Chisholm" },
  { rank: 417, name: "Rusk" },
  { rank: 418, name: "Crandall" },
  { rank: 419, name: "Shady Hollow" },
  { rank: 420, name: "Giddings" },
  { rank: 421, name: "Sparks" },
  { rank: 422, name: "Horseshoe Bay" },
  { rank: 423, name: "Hudson" },
  { rank: 424, name: "Sansom Park" },
  { rank: 425, name: "Doffing" },
  { rank: 426, name: "Mineola" },
  { rank: 427, name: "Bullard" },
  { rank: 428, name: "Gilmer" },
  { rank: 429, name: "Center" },
  { rank: 430, name: "Port Isabel" },
  { rank: 431, name: "Breckenridge" },
  { rank: 432, name: "Zapata" },
  { rank: 433, name: "Progreso" },
  { rank: 434, name: "Caddo Mills" },
  { rank: 435, name: "Terrell Hills" },
  { rank: 436, name: "Nassau Bay" }
]

interface TexasCitySelectorProps {
  onCitySelect: (city: City) => void
  selectedCities: string[]
}

const TexasCitySelector: React.FC<TexasCitySelectorProps> = ({ onCitySelect, selectedCities }) => {
  return (
    <div className="space-y-2">
      <label htmlFor="city-select" className="block text-sm font-medium text-[#E4B649]">
        Select a Texas City
      </label>
      <Select onValueChange={(value) => {
        const selectedCity = TEXAS_CITIES.find(city => city.name === value)
        if (selectedCity) onCitySelect(selectedCity)
      }}>
        <SelectTrigger id="city-select" className="w-full bg-black/50 border-[#E4B649]/20 text-white">
          <SelectValue placeholder="Choose a city" />
        </SelectTrigger>
        <SelectContent className="bg-black border-[#E4B649]/20">
          <ScrollArea className="h-[200px]">
            {TEXAS_CITIES.map((city) => (
              <SelectItem 
                key={city.rank} 
                value={city.name}
                className="text-white hover:bg-[#E4B649]/20"
                disabled={selectedCities.includes(city.name)}
              >
                {city.name}
              </SelectItem>
            ))}
          </ScrollArea>
        </SelectContent>
      </Select>
      <p className="text-xs text-[#E4B649]/70">
        * You can select up to 10 cities from Texas
      </p>
    </div>
  )
}

export default TexasCitySelector
